In [1]:
%matplotlib inline

In [22]:
import pandas as pd

import time
import numpy as np
import multiprocessing as mp
from multiprocessing import Pool
import csv
import re
import os
import bz2
from collections import defaultdict
from functools import reduce
from io import BytesIO

In [3]:
from ipywidgets import Button, VBox
VBox([Button(description='button 1')])

VBox(children=(Button(description='button 1', style=ButtonStyle()),))

In [2]:
from pandarallel import pandarallel

pandarallel.initialize(progress_bar=True)

INFO: Pandarallel will run on 20 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.

In [4]:
ratings_compositionality_modifiers=pd.read_csv('../data/NCC/Compositionality-Feature-NN/ratings-compositionality-modifiers.tsv',sep='\t',header=None)
ratings_compositionality_modifiers.columns=['compound','modifier','mod_comp']
#ratings_compositionality_modifiers=ratings_compositionality_modifiers.loc[ratings_compositionality_modifiers.mod_comp>=4]
ratings_compositionality_modifiers

                compound  modifier  mod_comp
0             Abiturnote    Abitur       4.6
1          Abiturzeugnis    Abitur       4.4
2           Ablagefläche    Ablage       4.6
3     Ablauforganisation    Ablauf       3.8
4         Abschiedsspiel  Abschied       3.6
...                  ...       ...       ...
1094   Zukunftsfähigkeit   Zukunft       4.4
1095             Öllampe        Öl       3.4
1096            Ölquelle        Öl       4.2
1097             Ölstand        Öl       4.6
1098         Übungssache     Übung       4.2

[1099 rows x 3 columns]

In [5]:
ratings_compositionality_heads=pd.read_csv('../data/NCC/Compositionality-Feature-NN/ratings-compositionality-heads.tsv',sep='\t',header=None)
ratings_compositionality_heads.columns=['compound','head','head_comp']
#ratings_compositionality_heads=ratings_compositionality_heads.loc[ratings_compositionality_heads.head_comp>=4]
ratings_compositionality_heads

                compound          head  head_comp
0             Abiturnote          Note        4.0
1          Abiturzeugnis       Zeugnis        4.2
2           Ablagefläche        Fläche        3.6
3     Ablauforganisation  Organisation        4.0
4         Abschiedsspiel         Spiel        3.4
...                  ...           ...        ...
1094   Zukunftsfähigkeit     Fähigkeit        3.4
1095             Öllampe         Lampe        3.8
1096            Ölquelle        Quelle        4.2
1097             Ölstand         Stand        3.8
1098         Übungssache         Sache        2.6

[1099 rows x 3 columns]

In [6]:
ratings_concreteness_modifiers=pd.read_csv('../data/NCC/Compositionality-Feature-NN/ratings-concreteness-modifiers.tsv',sep='\t',header=None)
ratings_concreteness_modifiers.columns=['compound','modifier','mod_conc']
#ratings_concreteness_modifiers=ratings_concreteness_modifiers.loc[ratings_concreteness_modifiers.mod_conc>=4]
ratings_concreteness_modifiers

                compound  modifier  mod_conc
0             Abiturnote    Abitur       2.2
1          Abiturzeugnis    Abitur       2.2
2           Ablagefläche    Ablage       2.0
3     Ablauforganisation    Ablauf       1.2
4         Abschiedsspiel  Abschied       2.2
...                  ...       ...       ...
1094   Zukunftsfähigkeit   Zukunft       0.4
1095             Öllampe        Öl       4.4
1096            Ölquelle        Öl       4.2
1097             Ölstand        Öl       4.8
1098         Übungssache     Übung       1.2

[1099 rows x 3 columns]

In [7]:
ratings_concreteness_heads=pd.read_csv('../data/NCC/Compositionality-Feature-NN/ratings-concreteness-heads.tsv',sep='\t',header=None)
ratings_concreteness_heads.columns=['compound','head','head_conc']
#ratings_concreteness_heads=ratings_concreteness_heads.loc[ratings_concreteness_heads.head_conc>=4]
ratings_concreteness_heads

                compound          head  head_conc
0             Abiturnote          Note        2.4
1          Abiturzeugnis       Zeugnis        4.2
2           Ablagefläche        Fläche        4.2
3     Ablauforganisation  Organisation        1.2
4         Abschiedsspiel         Spiel        2.6
...                  ...           ...        ...
1094   Zukunftsfähigkeit     Fähigkeit        1.0
1095             Öllampe         Lampe        4.6
1096            Ölquelle        Quelle        3.6
1097             Ölstand         Stand        1.6
1098         Übungssache         Sache        2.8

[1099 rows x 3 columns]

In [8]:
ratings_concreteness_compounds=pd.read_csv('../data/NCC/Compositionality-Feature-NN/ratings-concreteness-compounds.tsv',sep='\t',header=None)
ratings_concreteness_compounds.columns=['compound','comp_conc']
#ratings_concreteness_compounds=ratings_concreteness_compounds.loc[ratings_concreteness_compounds.comp_conc>=4]
ratings_concreteness_compounds

                compound  comp_conc
0             Abiturnote        2.6
1          Abiturzeugnis        4.4
2           Ablagefläche        4.6
3     Ablauforganisation        1.0
4         Abschiedsspiel        2.6
...                  ...        ...
1094   Zukunftsfähigkeit        0.4
1095             Öllampe        4.6
1096            Ölquelle        4.4
1097             Ölstand        3.6
1098         Übungssache        0.8

[1099 rows x 2 columns]

In [9]:
ratings_hypernymy=pd.read_csv('../data/NCC/Compositionality-Feature-NN/ratings-hypernymy.tsv',sep='\t',header=None)
ratings_hypernymy.columns=['compound','head','head_hyper']
#ratings_hypernymy=ratings_hypernymy.loc[ratings_hypernymy.head_hyper>=4]
ratings_hypernymy

                compound          head  head_hyper
0             Abiturnote          Note         4.8
1          Abiturzeugnis       Zeugnis         5.0
2           Ablagefläche        Fläche         4.4
3     Ablauforganisation  Organisation         4.4
4         Abschiedsspiel         Spiel         4.6
...                  ...           ...         ...
1094   Zukunftsfähigkeit     Fähigkeit         4.0
1095             Öllampe         Lampe         5.0
1096            Ölquelle        Quelle         4.6
1097             Ölstand         Stand         3.2
1098         Übungssache         Sache         2.0

[1099 rows x 3 columns]

In [10]:
compound_ratings_dfs=[ratings_compositionality_modifiers,ratings_compositionality_heads,
                      ratings_concreteness_modifiers,ratings_concreteness_heads,ratings_concreteness_compounds,
                      ratings_hypernymy]

In [11]:
compound_ratings=reduce(lambda  left,right: pd.merge(left,right,on=['compound'],suffixes=('', '_y')), compound_ratings_dfs)
compound_ratings.drop(['modifier_y','head_y','head_y'],axis=1,inplace=True)
compound_ratings

,compound,modifier,mod_comp,head,head_comp,mod_conc,head_conc,comp_conc,head_hyper
0,Abiturnote,Abitur,4.6,Note,4.0,2.2,2.4,2.6,4.8
1,Abiturzeugnis,Abitur,4.4,Zeugnis,4.2,2.2,4.2,4.4,5.0
2,Ablagefläche,Ablage,4.6,Fläche,3.6,2.0,4.2,4.6,4.4
3,Ablauforganisation,Ablauf,3.8,Organisation,4.0,1.2,1.2,1.0,4.4
4,Abschiedsspiel,Abschied,3.6,Spiel,3.4,2.2,2.6,2.6,4.6
...,...,...,...,...,...,...,...,...,...
1094,Zukunftsfähigkeit,Zukunft,4.4,Fähigkeit,3.4,0.4,1.0,0.4,4.0
1095,Öllampe,Öl,3.4,Lampe,3.8,4.4,4.6,4.6,5.0
1096,Ölquelle,Öl,4.2,Quelle,4.2,4.2,3.6,4.4,4.6
1097,Ölstand,Öl,4.6,Stand,3.8,4.8,1.6,3.6,3.2
1098,Übungssache,Übung,4.2,Sache,2.6,1.2,2.8,0.8,2.0

In [12]:
mod_list=compound_ratings.modifier.unique().tolist()
head_list=compound_ratings['head'].unique().tolist()
comp_list=compound_ratings.compound.unique().tolist()

features_modifiers=pd.read_csv('Compositionality-Feature-NN/features-compounds.tsv',sep='\t',header=None)
#features_modifiers.columns=['compound','modifier','mod_conc']
features_modifiers

In [17]:
cur_path='../data/NCC/dewiktionary-20240201-pages-articles.xml.bz2'

In [18]:
with bz2.open(cur_path, "rb") as bz_file:
    xml_data=bz_file.read()

element_list = []
for event, element in etree.iterparse(trial_xml):
    element_list.append(etree.tostring(element))
    element.clear()
element_list[:10]

In [24]:
xml_df = pd.read_xml(BytesIO(xml_data),
         iterparse = {"page": ["title", "text"]})

In [67]:
xml_df=xml_df.loc[xml_df.title.str.contains(':')==False]
xml_df

                     title                                               text
166                  Hallo  {{Siehe auch|[[hallo]], [[halló]]}}\n== Hallo ...
182                   ordo  {{Siehe auch|[[Ordo]]}}\n== ōrdo ({{Sprache|La...
183                familia  {{Siehe auch|[[família]]}}\n== familia ({{Spra...
184                species  {{Siehe auch|[[Species]]}}\n== species ({{Spra...
185                classis  {{Siehe auch|[[Classis]]}}\n== classis ({{Spra...
...                    ...                                                ...
1246620   Tales der Könige  == Tales der Könige ({{Sprache|Deutsch}}) ==\n...
1246621    Tals der Könige  == Tals der Könige ({{Sprache|Deutsch}}) ==\n=...
1246622  Vorverkaufsgebühr  == Vorverkaufsgebühr ({{Sprache|Deutsch}}) ==\...
1246623       planetarisch  == planetarisch ({{Sprache|Deutsch}}) ==\n=== ...
1246624             beatum  == beatum ({{Sprache|Latein}}) ==\n=== {{Worta...

[1110877 rows x 2 columns]

In [154]:
german_df=xml_df.loc[xml_df.text.str.contains('Sprache\|Deutsch')]
#german_df.text=german_df.text.str.replace('(\{\{Siehe auch\|.*\}\})(\n\n)','\\1\n',regex=True)
#german_df=german_df.loc[~((german_df.text.str.count('=== \{\{Wortart\|.* ===')==1) & (german_df.text.str.contains('=== \{\{Wortart\|(Deklinierte Form|Konjugierte Form)\|Deutsch\}\} ===')==True))]
#german_df=german_df.loc[german_df.text.str.count('=== \{\{Wortart\|.* ===')>1]
#german_df=german_df.loc[~((german_df.text.str.count('=== \{\{Wortart\|.* ===')==2) & (german_df.text.str.contains('=== \{\{Wortart\|Konjugierte Form\|Deutsch\}\} ===')==True) & (german_df.text.str.contains('=== \{\{Wortart\|Deklinierte Form\|Deutsch\}\} ===')==True))]
german_df

                     title                                               text
166                  Hallo  {{Siehe auch|[[hallo]], [[halló]]}}\n== Hallo ...
186             Subfamilia  == Subfamilia ({{Sprache|Deutsch}}) ==\n=== {{...
189              Subregnum  == Subregnum ({{Sprache|Deutsch}}) ==\n=== {{W...
190             Subdivisio  == Subdivisio ({{Sprache|Deutsch}}) ==\n=== {{...
191                 Phylum  {{Siehe auch|[[phylum]]}}\n== Phylum ({{Sprach...
...                    ...                                                ...
1246619     Tal der Könige  == Tal der Könige ({{Sprache|Deutsch}}) ==\n==...
1246620   Tales der Könige  == Tales der Könige ({{Sprache|Deutsch}}) ==\n...
1246621    Tals der Könige  == Tals der Könige ({{Sprache|Deutsch}}) ==\n=...
1246622  Vorverkaufsgebühr  == Vorverkaufsgebühr ({{Sprache|Deutsch}}) ==\...
1246623       planetarisch  == planetarisch ({{Sprache|Deutsch}}) ==\n=== ...

[863053 rows x 2 columns]

Affix,Präfix,Suffix,Interfix,Zirkumfix,

Affixoid,Präfixoid,Suffixoid,

Enklitikon

Flektierte Form,Deklinierte Form,Dekliniertes Gerundivum,Erweiterter Infinitiv,Komparativ,Konjugierte Form,Superlativ

Gebundenes Lexem

Deklinierte Form (Deutsch)‎ (2 Kategorien, 443917 Seiten)
 Erweiterter Infinitiv (Deutsch)‎ (5886 Seiten)
 Komparativ (Deutsch)‎ (5948 Seiten)
 Konjugierte Form (Deutsch)‎ (210707 Seiten)
 Superlativ (Deutsch)‎ (5946 Seiten)

In [155]:
noun_df=german_df.loc[german_df.text.str.contains('\{\{Wortart\|Substantiv\|Deutsch\}\}')]
noun_df

                     title                                               text
166                  Hallo  {{Siehe auch|[[hallo]], [[halló]]}}\n== Hallo ...
186             Subfamilia  == Subfamilia ({{Sprache|Deutsch}}) ==\n=== {{...
189              Subregnum  == Subregnum ({{Sprache|Deutsch}}) ==\n=== {{W...
190             Subdivisio  == Subdivisio ({{Sprache|Deutsch}}) ==\n=== {{...
191                 Phylum  {{Siehe auch|[[phylum]]}}\n== Phylum ({{Sprach...
...                    ...                                                ...
1246608         Luftwirbel  == Luftwirbel ({{Sprache|Deutsch}}) ==\n=== {{...
1246609         Anknüpfung  == Anknüpfung ({{Sprache|Deutsch}}) ==\n=== {{...
1246618         Muffigkeit  == Muffigkeit ({{Sprache|Deutsch}}) ==\n{{erwe...
1246619     Tal der Könige  == Tal der Könige ({{Sprache|Deutsch}}) ==\n==...
1246622  Vorverkaufsgebühr  == Vorverkaufsgebühr ({{Sprache|Deutsch}}) ==\...

[108357 rows x 2 columns]

In [145]:
german_df.loc[german_df.text.str.contains('Supinum')]

                    title                                               text
1788                   ha  {{Siehe auch|[[hä]], [[hā]]}}\n== ha! ({{Sprac...
2667             schlafen  {{Siehe auch|[[Schläfen]]}}\n{{Wort der Woche|...
14768             Supinum  == Supinum ({{Sprache|Deutsch}}) ==\n=== {{Wor...
62172   infinite Verbform  == infinite Verbform ({{Sprache|Deutsch}}) ==\...
84659    Verbalsubstantiv  == Verbalsubstantiv ({{Sprache|Deutsch}}) ==\n...
131077                fas  {{Siehe auch|[[fås]]}}\n== fas ({{Sprache|Deut...
255952           Supinums  == Supinums ({{Sprache|Deutsch}}) ==\n=== {{Wo...
261823             Supina  == Supina ({{Sprache|Deutsch}}) ==\n=== {{Wort...
383367          Absolutiv  == Absolutiv ({{Sprache|Deutsch}}) ==\n=== {{W...
412440           Lagewort  == Lagewort ({{Sprache|Deutsch}}) ==\n=== {{Wo...
975772         Supinstamm  == Supinstamm ({{Sprache|Deutsch}}) ==\n=== {{...

In [16]:
noun_df.loc[noun_df.text.str.count('=== {{Wortart\|.* ===')>1]

                 title                                               text
205              April  {{Siehe auch|[[april]], [[apríl]]}}\n== April ...
206                Mai  {{Siehe auch|[[mai]], [[MAI]], [[maí]]}}\n== M...
209             August  {{Siehe auch|[[august]]}}\n== August ({{Sprach...
210          September  {{Siehe auch|[[september]]}}\n== September ({{...
212           November  {{Siehe auch|[[november]], [[nóvember]]}}\n== ...
...                ...                                                ...
1241878       Bostoner  == Bostoner ({{Sprache|Deutsch}}) ==\n=== {{Wo...
1242767  Haftbedingung  == Haftbedingung ({{Sprache|Deutsch}}) ==\n===...
1242791       Bergbach  == Bergbach ({{Sprache|Deutsch}}) ==\n=== {{Wo...
1242901       Afrasiab  == Afrasiab ({{Sprache|Deutsch}}) ==\n=== {{Wo...
1243347           Sima  == Sima ({{Sprache|Deutsch}}) ==\n=== {{Wortar...

[4627 rows x 2 columns]

In [17]:
noun_df.loc[noun_df.title.str.count(" ")>0]

,title,text
2224,Geospiza conirostris,== Geospiza conirostris ({{Sprache|Deutsch}}) ...
2449,Otto Normalverbraucher,{{Siehe auch|[[Ottonormalverbraucher]]}}\n== O...
2698,Vereinigte Staaten,== Vereinigte Staaten ({{Sprache|Deutsch}}) ==...
2972,Gewinn- und Verlustrechnung,{{Siehe auch|[[Gewinn-und-Verlust-Rechnung]]}}...
3192,Delirium tremens,{{Siehe auch|[[delirium tremens]]}}\n== Deliri...
...,...,...
1241096,Nervus Rerum,== Nervus Rerum ({{Sprache|Deutsch}}) ==\n=== ...
1241211,Brand Manager,== Brand Manager ({{Sprache|Deutsch}}) ==\n===...
1241276,Trade Marketing Manager,== Trade Marketing Manager ({{Sprache|Deutsch}...
1241511,Coney Island,== Coney Island ({{Sprache|Deutsch}}) ==\n=== ...
1242046,Catskill Mountains,== Catskill Mountains ({{Sprache|Deutsch}}) ==...

In [78]:
noun_df.loc[noun_df.text.str.count('== .* \{\{Wortart\|.*\|Deutsch\}\} ==')>1].sample(20)

              title                                               text
368555     Kostroma  == Kostroma ({{Sprache|Deutsch}}) ==\n=== {{Wo...
2900          Simon  == Simon ({{Sprache|Deutsch}}) ==\n=== {{Worta...
12670        Elster  {{Siehe auch|[[ELSTER]]}}\n== Elster ({{Sprach...
4987           Hase  == Hase ({{Sprache|Deutsch}}) ==\n=== {{Wortar...
3891        München  == München ({{Sprache|Deutsch}}) ==\n=== {{Wor...
86410       Alphard  == Alphard ({{Sprache|Deutsch}}) ==\n=== {{Wor...
3162         Xander  == Xander ({{Sprache|Deutsch}}) ==\n=== {{Wort...
40592         Amber  == Amber ({{Sprache|Deutsch}}) ==\n=== {{Worta...
466708  Fichtelberg  == Fichtelberg ({{Sprache|Deutsch}}) ==\n=== {...
108155        Möser  {{Siehe auch|[[moser]], [[Moser]]}}\n== Möser ...
125221    Steinbach  == Steinbach ({{Sprache|Deutsch}}) ==\n=== {{W...
83332       Hidalgo  == Hidalgo ({{Sprache|Deutsch}}) ==\n=== {{Wor...
64814          Boom  {{Siehe auch|[[boom]]}}\n== Boom ({{Sprache|De...
331909       Emilia  == Emilia ({{Sprache|Deutsch}}) ==\n=== {{Wort...
10704         Lippe  == Lippe ({{Sprache|Deutsch}}) ==\n=== {{Worta...
8961     Montserrat  == Montserrat ({{Sprache|Deutsch}}) ==\n=== {{...
3959          Kenia  == Kenia ({{Sprache|Deutsch}}) ==\n=== {{Worta...
20721        Aurora  {{Siehe auch|[[aurora]]}}\n== Aurora ({{Sprach...
60784         Donga  {{Siehe auch|[[donga]]}}\n== Donga ({{Sprache|...
19221          Ried  == Ried ({{Sprache|Deutsch}}) ==\n{{erweitern|...

In [56]:
noun_df.loc[noun_df.text.str.count('== .* \({{Sprache\|.* ==')>1].sample(20)

                    title                                               text
75192              Marion  == Marion ({{Sprache|Deutsch}}) ==\n=== {{Wort...
382112             Recife  == Recife ({{Sprache|Deutsch}}) ==\n=== {{Wort...
21141           Darmstadt  == Darmstadt ({{Sprache|Deutsch}}) ==\n=== {{W...
20489            Mannheim  == Mannheim ({{Sprache|Deutsch}}) ==\n=== {{Wo...
40425                 Ada  {{Siehe auch|[[ada]], [[Adą]], [[āda]], [[ādā]...
12851               Baldo  == Baldo ({{Sprache|Deutsch}}) ==\n=== {{Worta...
40616              Gloria  {{Siehe auch|[[gloria]], [[glòria]]}}\n== Glor...
230640              Ajmer  == Ajmer ({{Sprache|Deutsch}}) ==\n=== {{Worta...
121793       Antananarivo  == Antananarivo ({{Sprache|Deutsch}}) ==\n=== ...
122148  Santiago de Chile  == Santiago de Chile ({{Sprache|Deutsch}}) ==\...
1813                    G  {{Siehe auch|[[g]], [[ġ]], [[Ġ]], [[ĝ]], [[Ĝ]]...
232776           Amarillo  {{Siehe auch|[[amarillo]]}}\n== Amarillo ({{Sp...
11927            Altamira  == Altamira ({{Sprache|Deutsch}}) ==\n=== {{Wo...
25267          Protestant  {{Siehe auch|[[protestant]]}}\n== Protestant (...
227948                Rus  {{Siehe auch|[[rus]]}}\n== Rus ({{Sprache|Deut...
20134                   Z  {{Siehe auch|[[z]], [[ź]], [[Ź]], [[ż]], [[Ż]]...
233911              Arras  {{Siehe auch|[[arras]]}}\n== Arras ({{Sprache|...
233604           Arequipa  == Arequipa ({{Sprache|Deutsch}}) ==\n=== {{Wo...
42219                   ä  {{Siehe auch|[[a]], [[A]], [[a-]], [[-a]], [[á...
234364             Austin  {{Siehe auch|[[āustin]]}}\n== Austin ({{Sprach...

In [158]:
trial_text=german_df.loc[german_df.title=='Muffigkeit'].text.values[0]
trial_text

"== Muffigkeit ({{Sprache|Deutsch}}) ==\n{{erweitern|Eintrag nach dem Homonym differenzieren, siehe [[muffig]] und Duden online|Deutsch}}\n=== {{Wortart|Substantiv|Deutsch}}, {{f}} ===\n\n{{Deutsch Substantiv Übersicht\n|Genus=f\n|Nominativ Singular=Muffigkeit\n|Nominativ Plural=—\n|Genitiv Singular=Muffigkeit\n|Genitiv Plural=—\n|Dativ Singular=Muffigkeit\n|Dativ Plural=—\n|Akkusativ Singular=Muffigkeit\n|Akkusativ Plural=—\n}}\n\n{{Worttrennung}}\n:Muf·fig·keit, {{kPl.}}\n\n{{Aussprache}}\n:{{IPA}} {{Lautschrift|ˈmʊfɪçkaɪ̯t}}, {{Lautschrift|ˈmʊfɪkkaɪ̯t}}\n:{{Hörbeispiele}} {{Audio|}}\n\n{{Bedeutungen}}\n:[1] Eigenschaft, muffig zu sein\n\n{{Beispiele}}\n:[1] „In den großen, hohen Räumen, geschmückt mit unmöglichen Tapeten und fast lächerlich verschnörkelten Stuckfriesen, herrschte eine deprimierende ''Muffigkeit'' und der Geruch fremdländischer Küche hing in der Luft, doch die Böden waren sauber, die Bettwäsche wurde in erträglichen Abständen gewechselt und das heiße Wasser wurde auch nicht allzu häufig kalt oder ganz abgedreht.“<ref>{{Literatur|Autor=H.P. Lovecraft|Titel=Kühle Luft|Sammelwerk=Das Gesamtwerk: Sämtliche Erzählungen und Zusammenarbeiten|Verlag=Festa|Ort=Leipzig|Jahr=2020|ISBN=978-3-865-52882-7|Seiten=568}}.</ref>\n\n==== {{Übersetzungen}} ====\n{{Ü-Tabelle|1|G=Eigenschaft, muffig zu sein|Ü-Liste=\n*{{en}}: {{Ü|en|}}\n*{{fr}}: {{Ü|fr|}}\n*{{it}}: {{Ü|it|}}\n*{{es}}: {{Ü|es|}}\n}}\n\n{{Referenzen}}\n:[*] {{Ref-DWDS-Korpus}}\n:[*] {{Ref-OWID}}\n:[1] {{Ref-Duden}}\n:[*] {{Ref-UniLeipzig}}\n\n{{Quellen}}"

In [16]:
to_match=re.findall('== .* \(\{\{Sprache\|.*\}\}\) ==',trial_text)
to_match

['== Altaisprache ({{Sprache|Deutsch}}) ==']

In [160]:
lst_1=trial_text.split('\n')
lst_1

['== Muffigkeit ({{Sprache|Deutsch}}) ==',
 '{{erweitern|Eintrag nach dem Homonym differenzieren, siehe [[muffig]] und Duden online|Deutsch}}',
 '=== {{Wortart|Substantiv|Deutsch}}, {{f}} ===',
 '',
 '{{Deutsch Substantiv Übersicht',
 '|Genus=f',
 '|Nominativ Singular=Muffigkeit',
 '|Nominativ Plural=—',
 '|Genitiv Singular=Muffigkeit',
 '|Genitiv Plural=—',
 '|Dativ Singular=Muffigkeit',
 '|Dativ Plural=—',
 '|Akkusativ Singular=Muffigkeit',
 '|Akkusativ Plural=—',
 '}}',
 '',
 '{{Worttrennung}}',
 ':Muf·fig·keit, {{kPl.}}',
 '',
 '{{Aussprache}}',
 ':{{IPA}} {{Lautschrift|ˈmʊfɪçkaɪ̯t}}, {{Lautschrift|ˈmʊfɪkkaɪ̯t}}',
 ':{{Hörbeispiele}} {{Audio|}}',
 '',
 '{{Bedeutungen}}',
 ':[1] Eigenschaft, muffig zu sein',
 '',
 '{{Beispiele}}',
 ":[1] „In den großen, hohen Räumen, geschmückt mit unmöglichen Tapeten und fast lächerlich verschnörkelten Stuckfriesen, herrschte eine deprimierende ''Muffigkeit'' und der Geruch fremdländischer Küche hing in der Luft, doch die Böden waren sauber, die Bettwäsche wurde in erträglichen Abständen gewechselt und das heiße Wasser wurde auch nicht allzu häufig kalt oder ganz abgedreht.“<ref>{{Literatur|Autor=H.P. Lovecraft|Titel=Kühle Luft|Sammelwerk=Das Gesamtwerk: Sämtliche Erzählungen und Zusammenarbeiten|Verlag=Festa|Ort=Leipzig|Jahr=2020|ISBN=978-3-865-52882-7|Seiten=568}}.</ref>",
 '',
 '==== {{Übersetzungen}} ====',
 '{{Ü-Tabelle|1|G=Eigenschaft, muffig zu sein|Ü-Liste=',
 '*{{en}}: {{Ü|en|}}',
 '*{{fr}}: {{Ü|fr|}}',
 '*{{it}}: {{Ü|it|}}',
 '*{{es}}: {{Ü|es|}}',
 '}}',
 '',
 '{{Referenzen}}',
 ':[*] {{Ref-DWDS-Korpus}}',
 ':[*] {{Ref-OWID}}',
 ':[1] {{Ref-Duden}}',
 ':[*] {{Ref-UniLeipzig}}',
 '',
 '{{Quellen}}']

In [91]:
indices_lst=[]
for cur_match in to_match:
    for i,cur_lst in enumerate(lst_1):
        if cur_match in cur_lst and i!=0:
            indices_lst.append(i)
indices_lst

[36]

In [73]:
import numpy as np

In [92]:
lang_lst=list(np.split(lst_1, indices_lst, axis=0))
lang_lst[0]

array(['{{Siehe auch|[[boom]]}}\n== Boom ({{Sprache|Deutsch}}) ==\n=== {{Wortart|Substantiv|Deutsch}}, {{m}} ===',
       "{{Deutsch Substantiv Übersicht\n|Genus=m\n|Nominativ Singular=Boom\n|Nominativ Plural=Booms\n|Genitiv Singular=Booms\n|Genitiv Plural=Booms\n|Dativ Singular=Boom\n|Dativ Plural=Booms\n|Akkusativ Singular=Boom\n|Akkusativ Plural=Booms\n|Bild=Konjunkturverlauf.svg|mini|1|Konjunkturverlauf in der Theorie: ''Boom'' grün markiert\n}}",
       '{{Worttrennung}}\n:Boom, {{Pl.}} Booms',
       '{{Aussprache}}\n:{{IPA}} {{Lautschrift|buːm}}\n:{{Hörbeispiele}} {{Audio|De-Boom.ogg}}\n:{{Reime}} {{Reim|uːm|Deutsch}}',
       '{{Bedeutungen}}\n:[1] {{K|Wirtschaft}} plötzliche Aufschwungsphase\n:[2] {{K|Börse}} [[Hausse]]\n:[3] {{K|übertr.}} Phase, in der etwas von großem Interesse ist oder häufig vorkommt',
       "{{Herkunft}}\n:entlehnt von englisch ''{{Ü|en|boom}}'' „brummen, brausen“<ref>{{Ref-Duden|Boom}}</ref>",
       '{{Synonyme}}\n:[1] [[Aufschwung]], [[Blütezeit]], [[Gipfel]], [[Hausse]], [[Hochkonjunktur]], [[Hochzeit]], [[Prosperität]]',
       '{{Gegenwörter}}\n:[1] [[Abschwung]], [[Rezession]], [[Stagnation]], [[Tal]]',
       '{{Unterbegriffe}}\n:[1] [[Biomasseboom]], [[Handelsboom]], [[Lithiumboom]], [[Nachkriegsboom]], [[Onlineboom]], [[Wirtschaftsboom]]\n:[2] [[Börsenboom]]\n:[3] [[Babyboom]], [[Bauboom]], [[Immobilienboom]], [[Kinderboom]], [[Reiseboom]], [[Touristenboom]], [[Tourismusboom]]',
       "{{Beispiele}}\n:[1] In der Wirtschaft folgt auf einen ''Boom'' meist ein Abschwung.\n:[1] Der ''Boom'' der Baubranche hält an.\n:[2] An der Börse steht ein ''Boom'' auch für einen Börsenhype, beziehungsweise für eine starke Börsenhausse, die von stark steigenden Aktienkursen auf breiter Front gekennzeichnet ist.<ref>{{Internetquelle|url=http://www.boersennews.de/lexikon/begriff/boom/1120|titel=börsennews.de|zugriff=2014-07-28}}</ref>\n:[3] Der Film löste unter Jugendlichen einen ''Boom'' aus.\n:[3] „Gleichsam als Kompensation ist ein ''Boom'' an Benimm-Büchern zu verzeichnen, und Etikette-Kurse haben Konjunktur.“<ref>{{Literatur |Autor= Werner Besch | Titel= Duzen, Siezen, Titulieren |TitelErg= Zur Anrede im Deutschen heute und gestern| Auflage= |Verlag= Vandenhoeck & Ruprecht| Ort= Göttingen| Jahr= 1996 | ISBN=3-525-33561-X | Seiten=131.}}</ref>",
       "{{Charakteristische Wortkombinationen}}\n:[1] [[anhaltend]]er ''Boom,'' einen ''Boom'' [[erleben]]",
       '{{Wortbildungen}}\n:[[boomen]], [[Boomer]]',
       '==== {{Übersetzungen}} ====\n{{Ü-Tabelle|1|G=Wirtschaft: plötzliche Aufschwungsphase|Ü-Liste=\n*{{da}}: {{Ü|da|boom}} {{n}}\n*{{en}}: {{Ü|en|boom}}\n*{{fr}}: {{Ü|fr|hausse}} {{f}}\n*{{it}}: {{Ü|it|boom}} {{m}}\n*{{nl}}: {{Ü|nl|boom}} {{m}}\n*{{no}}: {{Ü|no|boom}} {{m}}\n*{{ru}}: {{Üt|ru|бум}} {{m}}\n*{{sv}}: {{Ü|sv|boom}}\n}}',
       '{{Ü-Tabelle|2|G=Börse: Hausse|Ü-Liste=\n*{{sv}}: {{Ü|sv|boom}}\n}}',
       '{{Ü-Tabelle|3|G=übertragen: Phase, in der etwas von großem Interesse ist oder häufig vorkommt|Ü-Liste=\n*{{sv}}: {{Ü|sv|boom}}\n}}',
       '{{Referenzen}}\n:[1] {{Wikipedia}}\n:[1] {{Ref-DWDS}}\n:[1–3] {{Ref-Duden}}\n:[1] {{Ref-UniLeipzig}}\n:[1, 3] {{Ref-FreeDictionary}}',
       '{{Quellen}}',
       '=== {{Wortart|Substantiv|Deutsch}}, {{n}}, {{Wortart|Toponym|Deutsch}} ===',
       '{{Deutsch Toponym Übersicht\n}}',
       '{{Worttrennung}}\n:Boom, {{kPl.}}',
       '{{Aussprache}}\n:{{IPA}} {{Lautschrift|boːm}}, {{Lautschrift|boʊ̯m}}\n:{{Hörbeispiele}} {{Audio|}}\n:{{Reime}} {{Reim|oːm|Deutsch}}',
       '{{Bedeutungen}}\n:[1] [[Stadt]] in [[Belgien]]',
       '{{Oberbegriffe}}\n:[1] [[Stadt]]',
       "{{Beispiele}}\n:[1] ''Boom'' hat etwa 15.000 Einwohner.",
       '{{Wortbildungen}}\n:[[Boomer]], [[Boomerin]]',
       '==== {{Übersetzungen}} ====\n{{Ü-Tabelle|1|G=Stadt in Belgien|Ü-Liste=\n*{{en}}: {{Ü|en|}}\n}}',
       '{{Referenzen}}\n:[1] {{Wikipedia|Boom (Belgien)}}',
       '=== {{Wortart|Substantiv|Deutsch}}, {{mf}}, {{Wortart|Nachname|Deutsch}} ===',
       '{{Deutsch Nachname Übersicht\n}}',
       '{{Worttrennung}}\n:Boom, {{Pl.}} Booms',
       '{{Aussprache}}\n:{{IPA}} {{Lautschrift|boːm}}\n:{{Hörbeispiele}} {{Audio|}}\n:{{Reime}} {{Reim|oːm|Deutsch}}',
       '{{Bedeutungen}}\n:[1] [[Familienname]]',
       '{{Namensvarianten}}\n:[[Bohm]]',
       '{{Bekannte Namensträger}}\n:[1] [[w:Pierre Boom|Pierre]] und [[w:Christel Boom|Christel Boom]]',
       "{{Beispiele}}\n:[1] Frau ''Boom'' mag impressionistische Malerei.",
       '{{Referenzen}}\n:[1]'], dtype='<U853')

In [93]:
lang_lst[1]

array(['== Boom ({{Sprache|Niederdeutsch}}) ==\n=== {{Wortart|Substantiv|Niederdeutsch}}, {{m}} ===',
       '{{Niederdeutsch Substantiv Übersicht\n|Wer oder was? (Einzahl)=de Boom\n|Wer oder was? (Mehrzahl 1)=de Bööm\n|Wer oder was? (Mehrzahl 2)=de Böme\n|Wen oder Wem? (Einzahl)=den Boom\n|Wen oder Wem? (Mehrzahl 1)=de Bööm\n|Wen oder Wem? (Mehrzahl 2)=de Böme\n}}',
       "{{Alternative Schreibweisen}}\n:''ostfälisch:'' [[bäom]] (Wilhelm Busch)",
       "{{Nebenformen}}\n:''mecklenburgisch:'' [[Baum]], {{Pl.}} Bäum; ''Heidjerplatt:'' Baum, {{Pl.}} Bäume",
       '{{Worttrennung}}\n:Boom, {{Pl.}} Bööm, {{Pl.2}} Bö·me',
       '{{Aussprache}}\n:{{IPA}} {{Lautschrift|boʊ̯m~bəʊ̯m}}\n:{{Hörbeispiele}} {{Audio|}}',
       '{{Bedeutungen}}\n:[1] [[Baum]]',
       '{{Oberbegriffe}}\n:[1] [[Plant]]',
       '{{Unterbegriffe}}\n:[1] [[Böök]], [[Dann]] ([[Dannenboom]]), [[Eek]] ([[Ekenboom]]), [[Iser]] ([[Isernboom]]), [[Wichel]]',
       "{{Beispiele}}\n:[1] Dat is’n ''Boom.''\n::Das ist ein ''Baum.''",
       '==== {{Übersetzungen}} ====\n{{Ü-Tabelle|1|G=Baum|Ü-Liste=\n*{{de}}: {{Ü|de|Baum}} {{m}}\n*{{en}}: {{Ü|en|tree}}\n*{{es}}: {{Ü|es|}}\n}}',
       '{{Referenzen}}\n:[1] {{Wikipedia|spr=nds|Boom}}\n:[1] {{Ref-Plattmakers|Boom}}\n:[1] {{Ref-Hansen|Boom|110}}',
       '{{Ähnlichkeiten 1|[[Biom]], [[Bohm]], [[Brom]], [[Dom]], [[doom]], [[Zoom]], [[zoom]]}}',
       '[[Kategorie:Entlehnung aus dem Englischen (Deutsch)]]'],
      dtype='<U853')

In [94]:
re.findall('=== {{Wortart\|.* ===',trial_text)

['=== {{Wortart|Substantiv|Deutsch}}, {{m}} ===',
 '=== {{Wortart|Substantiv|Deutsch}}, {{n}}, {{Wortart|Toponym|Deutsch}} ===',
 '=== {{Wortart|Substantiv|Deutsch}}, {{mf}}, {{Wortart|Nachname|Deutsch}} ===',
 '=== {{Wortart|Substantiv|Niederdeutsch}}, {{m}} ===']

In [91]:
re.search(r"={{Siehe auch|\[\[(.*?)\]\]}}", trial_text).group(1)

'hallo]], [[halló'

In [79]:
re.search(r"=== {{Wortart\|(.*?)\|(.*?)}} ===", trial_text).group(2)

'Deutsch}}, {{m'

In [75]:
import re

def extract_wiktionary_info(text):
    # Extracting word type and gender
    word_type_match = re.search(r"=== {{Wortart\|(.*?)\|(.*?)}} ===", text)
    if word_type_match:
        word_type = word_type_match.group(1)
        gender = word_type_match.group(2)
        print("Word Type:", word_type)
        print("Gender:", gender)

    # Extracting declensions
    declensions_match = re.search(r"{{Deutsch Substantiv Übersicht\n\|(.*?)\n}}", text, re.DOTALL)
    if declensions_match:
        declensions_data = declensions_match.group(1)
        print("Declensions:", declensions_data)

    # Extracting pronunciation
    pronunciation_match = re.search(r":{{IPA}} {{Lautschrift\|(.*?)}}", text)
    if pronunciation_match:
        pronunciation = pronunciation_match.group(1)
        print("Pronunciation:", pronunciation)

    # Extracting meanings
    meanings_match = re.search(r"{{Bedeutungen}}\n:(.*?)\n", text, re.DOTALL)
    if meanings_match:
        meanings = meanings_match.group(1)
        print("Meanings:", meanings)

    # Extracting synonyms
    synonyms_match = re.search(r"{{Synonyme}}\n:(.*?)\n", text, re.DOTALL)
    if synonyms_match:
        synonyms = synonyms_match.group(1)
        print("Synonyms:", synonyms)

    # Extracting examples
    examples_match = re.search(r"{{Beispiele}}\n:(.*?)\n", text, re.DOTALL)
    if examples_match:
        examples = examples_match.group(1)
        print("Examples:", examples)

    # Extracting translations
    translations_match = re.search(r"==== {{Übersetzungen}} ====\n(.*?)\n{{Referenzen}}", text, re.DOTALL)
    if translations_match:
        translations = translations_match.group(1)
        print("Translations:", translations)

if __name__ == "__main__":
    wiktionary_text = ''' ... (the provided content) ... '''
    extract_wiktionary_info(wiktionary_text)

In [100]:
trial_text.split('\n')

['== Altstadt ({{Sprache|Deutsch}}) ==',
 '=== {{Wortart|Substantiv|Deutsch}}, {{f}} ===',
 '',
 '{{Deutsch Substantiv Übersicht',
 '|Genus=f',
 '|Nominativ Singular=Altstadt',
 '|Nominativ Plural=Altstädte',
 '|Genitiv Singular=Altstadt',
 '|Genitiv Plural=Altstädte',
 '|Dativ Singular=Altstadt',
 '|Dativ Plural=Altstädten',
 '|Akkusativ Singular=Altstadt',
 '|Akkusativ Plural=Altstädte',
 "|Bild 1=SalzburgerAltstadt02b.jpg|mini|1|die ''Altstadt'' von [[Salzburg]]",
 "|Bild 2=|mini|1|''Altstadt'' von [[Königsberg]] (nunmehr [[Kaliningrad]])",
 '}}',
 '',
 '{{Worttrennung}}',
 ':Alt·stadt, {{Pl.}} Alt·städ·te',
 '',
 '{{Aussprache}}',
 ':{{IPA}} {{Lautschrift|ˈaltˌʃtat}}',
 ':{{Hörbeispiele}} {{Audio|De-Altstadt.ogg}}',
 ':{{Reime}} {{Reim|altʃtat|Deutsch}}',
 '',
 '{{Bedeutungen}}',
 ':[1] der älteste Teil einer Stadt, sofern dieser (typischerweise) vor 1900 gebaut wurde oder in einem entsprechendem Stil wiederaufgebaut worden ist',
 '',
 '{{Herkunft}}',
 ":[[Determinativkompositum]] aus ''[[alt]]'' und ''[[Stadt]]''",
 '',
 '{{Sinnverwandte Wörter}}',
 ':[1] [[Altort]], [[Innenstadt]]',
 '',
 '{{Gegenwörter}}',
 ':[1] [[Neustadt]]',
 '',
 '{{Oberbegriffe}}',
 ':[1] [[Stadtteil]]',
 '',
 '{{Beispiele}}',
 ":[1] In der ''Altstadt'' von Prag gibt es Gebäude aus dem 14. Jahrhundert.",
 ":[1] Seit Ende des Zweiten Weltkrieges hat Berlin keine ''Altstadt'' mehr.",
 ":[1] „Der Reiseführer setzte unbeirrt seine Tour fort, und bald darauf betraten wir die ''Altstadt'' von Kairo mit ihren vielen Kirchen.“<ref>{{Literatur|Autor=Hamed Abdel-Samad|Titel=Mein Abschied vom Himmel|TitelErg= Aus dem Leben eines Muslims Deutschland |Verlag=Knaur Taschenbuch Verlag |Ort=München|Jahr= 2010|Seiten= 176|ISBN= 978-3-426-78408-2}}.</ref>",
 ":[1] „Es hat mich immer gewundert, dass die Neustadt so hieß, obwohl dort viel mehr alte und verfallene Häuser standen als in der ''Altstadt,'' die nach der Zerstörung größtenteils abgerissen und neu gebaut wurde. Eine neue ''Altstadt,'' funktional und uncharmant.“<ref>{{Literatur|Autor=Jan Josef Liefers|Titel=Soundtrack meiner Kindheit|Verlag=Rowohlt|Ort= Reinbek|Jahr=2011|Seiten=199.|ISBN= 978-3-499-62592-3}}</ref>",
 ":[1] „Sie mündet in die Warschauer ''Altstadt,'' der man es ebenfalls nicht ansieht, daß sie nur vierzig Jahre alt ist.“<ref>{{Literatur|Autor=Radek Knapp|Titel=Gebrauchsanweisung für Polen|Auflage=5.|Verlag=Piper|Ort= München, Zürich |Jahr=2011}}, Seite 38. ISBN 978-3-423-492-27536-1.</ref>",
 ":[1] „Im Rahmen der BUGA entsteht hier ein attraktiver, großzügiger Landschaftspark, der einen Gegenpol zu dem regen Leben in der ''Altstadt'' bietet.“<ref>{{Literatur | Autor= Joana Müller |Herausgeber= Thomas Brühne, Stefan Harnischmacher |Titel= Koblenz blüht auf: Die BUGA 2011 als Chance einer nachhaltigen Stadtentwicklung |Sammelwerk= Koblenz und sein Umland. Eine Auswahl geographischer Exkursionen | Verlag= Bouvier | Ort= Bonn | Jahr=2011 | Seiten= 30-37, Zitat Seite 31.| ISBN=978-3-416-03338-1}}</ref>",
 '',
 '{{Wortbildungen}}',
 ':[[Altstadterhaltungsfonds]], [[Altstadtmauer]], [[Altstadtquartier]], [[Altstadtpflaster]], [[Altstadtsanierung]], [[Altstadttor]], [[Altstadtviertel]], [[Altstadtwochenmarkt]]',
 '',
 '==== {{Übersetzungen}} ====',
 '{{Ü-Tabelle|1|G=|Ü-Liste=',
 '*{{en}}: {{Ü|en|old town}}',
 '*{{fi}}: {{Ü|fi|vanhakaupunki}}',
 '*{{fr}}: {{Ü|fr|vieille ville}} {{f}}, {{Ü|fr|centre historique}} {{m}}',
 '*{{it}}: {{Ü|it|città vecchia}} {{f}}, {{Ü|it|centro storico}} {{m}}',
 '*{{ja}}: {{Üt|ja|旧市街|きゅうしがい, kyōshigai}}',
 '*{{ca}}: {{Ü|ca|centre històric}} {{m}}',
 '*{{hr}}: {{Ü|hr|stari grad}} {{m}}, {{Ü|hr|povijesna jezgra}} {{f}}',
 '*{{lt}}: {{Ü|lt|senamiestis}}',
 '*{{lb}}: {{Ü|lb|Alstad}} {{f}}',
 '*{{nl}}: {{Ü|nl|historisch centrum}} {{n}}, {{Ü|nl|oudestad}} {{f}}',
 '*{{pt}}: {{Ü|pt|bairro histórico}} {{m}}, {{Ü|pt|centro histórico}} {{m}}',
 '*{{ru}}: {{Üt|ru|старый город}} {{m}}',
 '*{{sv}}: {{Ü|sv|gammal stadskärna}} {{u}}',
 '*{{es}}: {{Ü|es|casco histórico}} {{m}}',
 '*{{tr}}: {{Ü|tr|eski şehir}}',
 '*{{hu}}: {{Ü|hu|óváros}}',
 '}}',
 '',
 '{{Referenzen}}',
 ':[1] {{Wikipedia|Altstadt}}',
 ':[1] {{Ref-Grimm|Altstadt}}',
 ':[1] {{Ref-DWDS|Altstadt}}',
 ':[1] {{Ref-UniLeipzig|Altstadt}}',
 ':[1] {{Ref-FreeDictionary|Altstadt}}',
 '',
 '{{Quellen}}',
 '',
 '=== {{Wortart|Substantiv|Deutsch}}, {{Wortart|Toponym|Deutsch}} {{n}} ===',
 '',
 '{{Deutsch Toponym Übersicht',
 '}}',
 '',
 '{{Worttrennung}}',
 ':Alt·stadt, {{kPl.}}',
 '',
 '{{Aussprache}}',
 ':{{IPA}} {{Lautschrift|ˈaltˌʃtat}}',
 ':{{Hörbeispiele}} {{Audio|De-Altstadt.ogg}}',
 ':{{Reime}} {{Reim|altʃtat|Deutsch}}',
 '',
 '{{Bedeutungen}}',
 ':[1] Ort im [[Saarland]], Deutschland',
 '',
 '{{Beispiele}}',
 ":[1] Anne wurde in ''Altstadt'' geboren.",
 '',
 '{{Referenzen}}',
 ':[1] {{Wikipedia|Altstadt (Kirkel)}}']

In [3]:
%matplotlib inline

In [4]:
import pandas as pd
import fasttext

import time
import numpy as np
import multiprocessing as mp
from multiprocessing import Pool
import csv
import spacy
import re
import warnings
import os
import base64
from lxml import etree
from collections import defaultdict
from functools import reduce

In [5]:
from ipywidgets import Button, VBox
VBox([Button(description='button 1')])

VBox(children=(Button(description='button 1', style=ButtonStyle()),))

In [2]:
from pandarallel import pandarallel

pandarallel.initialize(progress_bar=True)

INFO: Pandarallel will run on 20 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.

In [6]:
fmodel = fasttext.load_model('/home/users0/pageljs/dh/repos/lid.176.bin')

Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

In [7]:
def b64_to_str(row):
    return base64.b64decode(row).decode('utf-8').split('\n')

In [8]:
def lang_detect(sent):
    
    label,_=fmodel.predict(sent,k=-1)
    return label[0]

In [9]:
#parser = spacy.load('en_core_web_lg')

sent_segmenter=spacy.load('de_core_news_lg')
sent_segmenter.disable_pipes(['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner'])
sent_segmenter.enable_pipe("senter")
sent_segmenter.add_pipe("doc_cleaner")
sent_segmenter.max_length=100_000_000

In [7]:
df=pd.read_csv('/fs/scratch/users/pageljs/VirtualBargaining/news-docs.2022.de.filtered',sep='\t',header=None,usecols=[1])
df['text']=df[1].parallel_apply(b64_to_str)
df.drop(1,axis=1,inplace=True)
df

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=133630), Label(value='0 / 133630')…

                                                      text
0        [Texas: Tochter musste wochenlang neben verwes...
1        [Thich Nhat Hanh ist tot, Die zahlreichen Büch...
2        [Katrin Göring-Eckardt: 58-Jähriger wegen Bele...
3        [Donald Trump: Ex-Sprecherin berichtet von geh...
4        [Fall Gabby Petito: Freund bekannte sich laut ...
...                                                    ...
2672577  [Mit Lidl E-Autos einfach und bequem zuhause o...
2672578  [Singen ... nicht nur zur Weihnachtszeit / Kos...
2672579  [Black is beautiful: Smarter Kaminofen ganz in...
2672580  [Bislang hat sich Scholz nicht als leidenschaf...
2672581  [Kölner Kardinal Woelki gibt neue eidesstattli...

[2672582 rows x 1 columns]

In [8]:
sent_df=df.explode('text')
sent_df.reset_index(inplace=True)
sent_df.columns=['doc_id','sent']
sent_df=sent_df.loc[sent_df.sent!=""]
sent_df=sent_df.loc[sent_df.sent.str.len()<1000]
sent_df['lang']=sent_df['sent'].parallel_apply(lang_detect)
sent_df=sent_df.loc[sent_df.lang=="__label__de"]
sent_df

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=2965001), Label(value='0 / 2965001…

,doc_id,sent,lang
0,0,Texas: Tochter musste wochenlang neben verwese...,__label__de
1,0,Die Polizei in Texas hat eine Frau in Gewahrsa...,__label__de
2,0,"Sie erklärte den Polizisten, sie habe den Tod ...",__label__de
3,0,US-Medienberichten zufolge lebten Mutter und T...,__label__de
4,0,Nachbarn informierten schließlich den örtliche...,__label__de
...,...,...,...
61974712,2672581,"Dahm hatte in einem Interview mit dem ""Kölner ...",__label__de
61974713,2672581,Nach Dahms Interview leitete die Kölner Staats...,__label__de
61974714,2672581,Auch in einem zweiten Fall ermittelt die Behör...,__label__de
61974715,2672581,Hier geht es um Woelkis Kenntnisstand über ein...,__label__de
61974716,2672581,Ein Verhandlungstermin vor dem Landgericht Köl...,__label__de

In [9]:
sent_df.iloc[0].sent

'Texas: Tochter musste wochenlang neben verwesender Leiche ihres Vaters leben'

In [10]:
ratings_compositionality_modifiers=pd.read_csv('Compositionality-Feature-NN/ratings-compositionality-modifiers.tsv',sep='\t',header=None)
ratings_compositionality_modifiers.columns=['compound','modifier','mod_comp']
ratings_compositionality_modifiers=ratings_compositionality_modifiers.loc[ratings_compositionality_modifiers.mod_comp>=4]
ratings_compositionality_modifiers

               compound modifier  mod_comp
0            Abiturnote   Abitur       4.6
1         Abiturzeugnis   Abitur       4.4
2          Ablagefläche   Ablage       4.6
6       Abzugsfähigkeit    Abzug       4.2
7           Ackerfläche    Acker       4.6
...                 ...      ...       ...
1093   Zukunftsaussicht  Zukunft       4.4
1094  Zukunftsfähigkeit  Zukunft       4.4
1096           Ölquelle       Öl       4.2
1097            Ölstand       Öl       4.6
1098        Übungssache    Übung       4.2

[555 rows x 3 columns]

In [11]:
ratings_compositionality_heads=pd.read_csv('Compositionality-Feature-NN/ratings-compositionality-heads.tsv',sep='\t',header=None)
ratings_compositionality_heads.columns=['compound','head','head_comp']
ratings_compositionality_heads=ratings_compositionality_heads.loc[ratings_compositionality_heads.head_comp>=4]
ratings_compositionality_heads

                compound          head  head_comp
0             Abiturnote          Note        4.0
1          Abiturzeugnis       Zeugnis        4.2
3     Ablauforganisation  Organisation        4.0
9             Ahornblatt         Blatt        4.2
10        Akustikgitarre       Gitarre        4.4
...                  ...           ...        ...
1085         Zipfelmütze         Mütze        4.8
1086      Zitronenpresse        Presse        4.2
1087        Zitronensaft          Saft        4.4
1093    Zukunftsaussicht      Aussicht        4.4
1096            Ölquelle        Quelle        4.2

[488 rows x 3 columns]

In [12]:
ratings_concreteness_modifiers=pd.read_csv('Compositionality-Feature-NN/ratings-concreteness-modifiers.tsv',sep='\t',header=None)
ratings_concreteness_modifiers.columns=['compound','modifier','mod_conc']
ratings_concreteness_modifiers=ratings_concreteness_modifiers.loc[ratings_concreteness_modifiers.mod_conc>=4]
ratings_concreteness_modifiers

         compound modifier  mod_conc
7     Ackerfläche    Acker       4.2
9      Ahornblatt    Ahorn       4.2
11      Alpenrand      Alp       4.6
25      Apfelsaft    Apfel       4.4
34        Armband      Arm       4.2
...           ...      ...       ...
1090  Zuckerwatte   Zucker       4.4
1092    Zugführer      Zug       4.4
1095      Öllampe       Öl       4.4
1096     Ölquelle       Öl       4.2
1097      Ölstand       Öl       4.8

[540 rows x 3 columns]

In [13]:
ratings_concreteness_heads=pd.read_csv('Compositionality-Feature-NN/ratings-concreteness-heads.tsv',sep='\t',header=None)
ratings_concreteness_heads.columns=['compound','head','head_conc']
ratings_concreteness_heads=ratings_concreteness_heads.loc[ratings_concreteness_heads.head_conc>=4]
ratings_concreteness_heads

            compound     head  head_conc
1      Abiturzeugnis  Zeugnis      4.200
2       Ablagefläche   Fläche      4.200
5     Abstandsfläche   Fläche      4.200
9         Ahornblatt    Blatt      4.800
10    Akustikgitarre  Gitarre      5.000
...              ...      ...        ...
1087    Zitronensaft     Saft      4.800
1088       Zollstock    Stock      5.000
1089       Zuckerhut      Hut      4.875
1090     Zuckerwatte    Watte      4.600
1095         Öllampe    Lampe      4.600

[494 rows x 3 columns]

In [14]:
ratings_concreteness_compounds=pd.read_csv('Compositionality-Feature-NN/ratings-concreteness-compounds.tsv',sep='\t',header=None)
ratings_concreteness_compounds.columns=['compound','comp_conc']
ratings_concreteness_compounds=ratings_concreteness_compounds.loc[ratings_concreteness_compounds.comp_conc>=4]
ratings_concreteness_compounds

            compound  comp_conc
1      Abiturzeugnis      4.400
2       Ablagefläche      4.600
7        Ackerfläche      4.400
9         Ahornblatt      4.800
10    Akustikgitarre      5.000
...              ...        ...
1088       Zollstock      5.000
1089       Zuckerhut      4.875
1090     Zuckerwatte      4.800
1095         Öllampe      4.600
1096        Ölquelle      4.400

[525 rows x 2 columns]

In [15]:
ratings_hypernymy=pd.read_csv('Compositionality-Feature-NN/ratings-hypernymy.tsv',sep='\t',header=None)
ratings_hypernymy.columns=['compound','head','head_hyper']
ratings_hypernymy=ratings_hypernymy.loc[ratings_hypernymy.head_hyper>=4]
ratings_hypernymy

                  compound          head  head_hyper
0               Abiturnote          Note         4.8
1            Abiturzeugnis       Zeugnis         5.0
2             Ablagefläche        Fläche         4.4
3       Ablauforganisation  Organisation         4.4
4           Abschiedsspiel         Spiel         4.6
...                    ...           ...         ...
1087          Zitronensaft          Saft         5.0
1091  Zugewinngemeinschaft  Gemeinschaft         4.0
1094     Zukunftsfähigkeit     Fähigkeit         4.0
1095               Öllampe         Lampe         5.0
1096              Ölquelle        Quelle         4.6

[739 rows x 3 columns]

In [16]:
compound_ratings_dfs=[ratings_compositionality_modifiers,ratings_compositionality_heads,
                      ratings_concreteness_modifiers,ratings_concreteness_heads,ratings_concreteness_compounds,
                      ratings_hypernymy]

In [17]:
compound_ratings=reduce(lambda  left,right: pd.merge(left,right,on=['compound'],suffixes=('', '_y')), compound_ratings_dfs)
compound_ratings.drop(['modifier_y','head_y','head_y'],axis=1,inplace=True)
compound_ratings

,compound,modifier,mod_comp,head,head_comp,mod_conc,head_conc,comp_conc,head_hyper
0,Ahornblatt,Ahorn,4.4,Blatt,4.2,4.2,4.8,4.8,5.0
1,Apfelsaft,Apfel,4.0,Saft,4.0,4.4,4.4,4.4,5.0
2,Bahnchef,Bahn,4.0,Chef,4.0,4.6,4.0,4.4,4.8
3,Bananenschale,Banane,4.8,Schale,4.2,5.0,5.0,5.0,5.0
4,Baumhaus,Baum,4.4,Haus,4.2,5.0,5.0,5.0,4.2
...,...,...,...,...,...,...,...,...,...
112,Wasserquelle,Wasser,4.4,Quelle,5.0,4.4,4.0,4.6,4.0
113,Wollschal,Wolle,4.2,Schal,4.6,4.4,5.0,5.0,5.0
114,Ziegelstein,Ziegel,4.2,Stein,4.2,4.0,4.4,4.4,4.4
115,Ziegenbock,Ziege,4.8,Bock,4.4,4.6,4.6,4.6,4.2
116,Zitronensaft,Zitrone,4.4,Saft,4.4,4.8,4.8,4.8,5.0

In [18]:
mod_list=compound_ratings.modifier.unique().tolist()
head_list=compound_ratings['head'].unique().tolist()
comp_list=compound_ratings.compound.unique().tolist()

features_modifiers=pd.read_csv('Compositionality-Feature-NN/features-compounds.tsv',sep='\t',header=None)
#features_modifiers.columns=['compound','modifier','mod_conc']
features_modifiers

In [19]:
germanet_compounds=pd.read_csv('/fs/scratch/users/pageljs/NCC/split_compounds_from_GermaNet18.0.txt',sep='\t',header=None)
germanet_compounds.drop([0,1],inplace=True)
germanet_compounds.columns=['compound','modifier','head']
germanet_compounds.drop_duplicates(subset='compound',inplace=True)
#germanet_compounds.modifier=germanet_compounds.modifier.str.split('|')
#germanet_compounds=germanet_compounds.explode('modifier')
germanet_compounds=germanet_compounds.loc[(germanet_compounds.modifier.isin(mod_list)) & (germanet_compounds['head'].isin(head_list))]
germanet_compounds

              compound modifier    head
1406         Ahornbaum    Ahorn    Baum
1407        Ahornblatt    Ahorn   Blatt
3549         Apfelbaum    Apfel    Baum
3557       Apfelgarten    Apfel  Garten
3560         Apfelkern    Apfel    Kern
...                ...      ...     ...
120541  Zitronenkuchen  Zitrone  Kuchen
120546    Zitronensaft  Zitrone    Saft
120548  Zitronenschale  Zitrone  Schale
120551     Zitronentee  Zitrone     Tee
120552  Zitronenwasser  Zitrone  Wasser

[410 rows x 3 columns]

In [20]:
def read_germanet_xml_nav(filename):
    synset_list = []
    tree = etree.parse(filename)
    synsets = tree.findall("synset")
    for synset in synsets:
        lexunits = synset.findall(".//lexUnit")
        paraphrase = synset.find(".//paraphrase")

        if paraphrase is not None:
            paraphrase_text = paraphrase.text
        else:
            paraphrase_text = None


        for lexunit in lexunits:
            orthForm = lexunit.find(".//orthForm")
            orthVar = lexunit.find(".//orthVar")
            if orthVar is not None:
                orthVar_text=orthVar.text
            else:
                orthVar_text=None
            compounds = lexunit.find(".//compound")
            if compounds is not None:
                compound = True
                modifiers = compounds.findall(".//modifier")

                #print(len(modifiers))
                for mod in modifiers:
                    if 'category' in mod.attrib:
                        mod_cat=mod.attrib["category"]
                    else:
                        mod_cat=None
                        
                    if len(modifiers)==2 and mod_cat=="Verb":
                        mod_cat="Nomen"
                        continue
                    else:
                        mod_text=mod.text
                        if 'property' in mod.attrib:
                            mod_prop=mod.attrib["property"]
                        else:
                            mod_prop=None
        

                head = compounds.find(".//head")
                head_text = head.text

                if 'property' in head.attrib:
                    head_prop=head.attrib["property"]
                else:
                    head_prop=None

            else:
                compound = False
                mod_text = None
                mod_cat=None
                head_text = None
                mod_prop=None
                head_prop=None
            synset_list.append({"synset_id": synset.attrib["id"],
                                "category": synset.attrib["category"],
                                "variation": orthVar_text,
                                "class": synset.attrib["class"],
                                "lexunit_id": lexunit.attrib["id"],
                                "sense": int(lexunit.attrib["sense"]),
                                "source": lexunit.attrib["source"],
                                "namedEntity": lexunit.attrib["namedEntity"],
                                "artificial": lexunit.attrib["artificial"],
                                "styleMarking": lexunit.attrib["styleMarking"],
                                "orthForm": orthForm.text,
                                "compound": compound,
                                "modifier": mod_text,
                                "head": head_text,
                                "modifier_cat":mod_cat,
                                "modifier_prop":mod_prop,
                                "head_prop":head_prop,
                               "paraphrase":paraphrase_text})
    return pd.DataFrame.from_dict(synset_list)

<!ELEMENT relations (lex_rel|con_rel)+>
<!ELEMENT lex_rel EMPTY>
<!ATTLIST lex_rel name 
      (has_antonym|has_participle|has_pertainym|has_active_usage|
      has_occasion|has_attribute|has_appearance|
      has_construction_method|has_container|is_container_for|
      has_consistency_of|has_component|has_owner|is_owner_of|has_function|
      has_manner_of_functioning|has_origin|has_production_method|
      has_content|has_no_property|has_habitat|has_location|is_location_of|
      has_measure|is_measure_of|has_material|has_member|is_member_of|
      has_diet|is_diet_of|has_eponym|has_user|has_product|is_product_of|
      has_prototypical_holder|is_prototypical_holder_for|
      has_prototypical_place_of_usage|has_relation|has_raw_product|
      has_other_property|is_storage_for|has_specialization|has_part|
      is_part_of|has_topic|is_caused_by|is_cause_for|is_comparable_to|
      has_usage|has_result_of_usage|has_purpose_of_usage|has_goods|
      has_time|is_access_to|has_ingredient|is_ingredient_of) #REQUIRED
                  dir  (one|both|revert) #REQUIRED
                  inv  CDATA #IMPLIED
                  from CDATA #REQUIRED
                  to   CDATA #REQUIRED>
<!ELEMENT con_rel EMPTY>
<!ATTLIST con_rel name (hyperonymy|meronymy|holonymy
        |entailment|causation|association) #REQUIRED
                  dir  (one|both|revert) #REQUIRED
                  inv  CDATA #IMPLIED
                  from CDATA #REQUIRED
                  to   CDATA #REQUIRED>


<con_rel name="hyperonymy" from="ID" to="ID" dir="revert" inv="hyponymy" />
<lex_rel name="antonymy" from="ID" to="ID" dir="both" />

In [21]:
def read_germanet_xml_rel(filename):

    tree = etree.parse(filename)
    #con_rels=tree.findall("con_rel")
    
    rels_list=[]
    #for con_rel in con_rels:
    
        #if 'inv' in con_rel.attrib:
            #inv_text=con_rel.attrib['inv']
        #else:
            #inv_text=None
        #rels_list.append({
                            #'rel_type':'con_rel',
                            #'name':con_rel.attrib["name"],
                             #'from':con_rel.attrib["from"],
                             #'to':con_rel.attrib["to"],
                             #'inv':inv_text})

    lex_rels=tree.findall("lex_rel")

    for lex_rel in lex_rels:
    
        if 'inv' in lex_rel.attrib:
            inv_text=lex_rel.attrib['inv']
        else:
            inv_text=None
        rels_list.append({
                            'rel_type':'lex_rel',
                            'name':lex_rel.attrib["name"],
                             'from':lex_rel.attrib["from"],
                             'to':lex_rel.attrib["to"],
                             'inv':inv_text})
    

    return pd.DataFrame.from_dict(rels_list)

<synset id="ID" wordCategory="CATEGORY">
  <lexUnit id="ID"  orthVarOf="VAR" acceptable="ACC" sense="SE" source="SRC" namedEntity="NE" artificial="AR" styleMarking="SM">
    <orthForm>ORTHFORM</orthForm>
    <orthVar>ORTHVAR</orthVar>
    <oldOrthForm>OLDORTHFORM</oldOrthForm>
    <oldOrthVar>OLDORTHVAR</oldOrthVar>
    <frame>FRAME</frame>
    <example>
      <text>TEXT</text>
      <exframe>EXFRAME</exframe>
    </example>
    <compound>
      <modifier property="PROP" category="CAT">MODIFIER1</modifier>
      <modifier property="PROP" category="CAT">MODIFIER2</modifier>
      <head property="PROP">HEAD</head>
    </compound>
  </lexUnit>
  <paraphrase>PARAPHRASE</paraphrase>
</synset>

In [22]:
import glob
noun_lists=glob.glob("/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen*")
#adj_lists=glob.glob("/resources/data/GermaNet/GN_V130/GN_V130_XML/adj*")
#verb_lists=glob.glob("/resources/data/GermaNet/GN_V130/GN_V130_XML/verben*")
#nav_lists=noun_lists+adj_lists+verb_lists
len(noun_lists)

23

In [23]:
df_list=[]

for lst in noun_lists:
    print(lst)
    cur_df=read_germanet_xml_nav(lst)
    df_list.append(cur_df)

germannet_df=pd.concat(df_list)

/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Attribut.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Gruppe.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Geschehen.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Substanz.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Koerper.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Kommunikation.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Artefakt.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Kognition.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Gefuehl.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Pflanze.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Mensch.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Motiv.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Nahrung.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.natPhaenomen.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Tier.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Form.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Zeit.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Besitz.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Menge.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Ort.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Tops.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.Relation.xml
/resources/data/GermaNet/GN_V130/GN_V130_XML/nomen.natGegenstand.xml

In [24]:
lexid_lst=germannet_df.lexunit_id.to_list()
word_lst=germannet_df.orthForm.to_list()
lexid_dict=dict(zip(lexid_lst,word_lst))

from collections import defaultdict
word_dict = defaultdict(list)
for k,v in lexid_dict.items():
    word_dict[v].append(k)

In [25]:
germannet_df.loc[germannet_df.orthForm.isin(comp_list)]

,synset_id,category,variation,class,lexunit_id,sense,source,namedEntity,artificial,styleMarking,orthForm,compound,modifier,head,modifier_cat,modifier_prop,head_prop,paraphrase
3197,s13169,nomen,None,Attribut,l18275,1,core,no,no,no,Haarfarbe,True,Haar,Farbe,Nomen,None,None,None
8664,s17018,nomen,None,Geschehen,l23661,1,core,no,no,no,Wasserquelle,True,Wasser,Quelle,Nomen,None,None,None
202,s67556,nomen,None,Substanz,l93477,1,core,no,no,no,Flusswasser,True,Fluss,Wasser,Nomen,None,None,None
1154,s48354,nomen,None,Substanz,l69056,1,core,no,no,no,Meerwasser,True,Meer,Wasser,Nomen,None,None,None
1155,s48354,nomen,None,Substanz,l86207,1,core,no,no,no,Seewasser,True,See,Wasser,Nomen,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4967,s110017,nomen,None,Ort,l145975,1,core,no,no,no,Standfläche,True,Stand,Fläche,Nomen,None,None,None
7446,s41605,nomen,None,Ort,l60756,1,core,no,no,no,Wandfläche,True,Wand,Fläche,Nomen,None,None,None
7630,s41588,nomen,None,Ort,l60738,1,core,no,no,no,Bürofläche,True,Büro,Fläche,Nomen,None,None,None
8111,s41604,nomen,None,Ort,l60755,1,core,no,no,no,Dachfläche,True,Dach,Fläche,Nomen,None,None,None
502,s40455,nomen,None,natGegenstand,l59250,1,core,no,no,no,Ziegelstein,True,Ziegel,Stein,Nomen,None,None,None

In [26]:
multi_sense_list=germannet_df.loc[(germannet_df.orthForm.isin(comp_list)) & (germannet_df.sense>1)].orthForm.to_list()
germannet_df.loc[germannet_df.orthForm.isin(multi_sense_list)]

,synset_id,category,variation,class,lexunit_id,sense,source,namedEntity,artificial,styleMarking,orthForm,compound,modifier,head,modifier_cat,modifier_prop,head_prop,paraphrase
2218,s47637,nomen,None,Substanz,l68161,2,core,no,no,no,Ziegelstein,True,Ziegel,Stein,Nomen,None,None,Baustoff aus tonhaltigem Lehm
11791,s10328,nomen,None,Artefakt,l14390,2,core,no,no,no,Vogelhaus,True,Vogel,Haus,Nomen,None,None,None
1846,s39908,nomen,None,Nahrung,l58522,2,core,no,no,no,Kamillentee,True,Kamille,Tee,Nomen,None,None,None
2459,s68580,nomen,None,Nahrung,l94679,1,core,no,no,no,Kamillentee,True,Kamille,Tee,Nomen,None,None,"getrocknete Kamillenblüten, welche zum Herstel..."
4693,s76625,nomen,None,Ort,l104428,2,core,no,no,no,Standfläche,True,Stand,Fläche,Nomen,None,None,None
4848,s132480,nomen,None,Ort,l173790,1,core,no,no,no,Vogelhaus,True,Vogel,Haus,Nomen,None,None,None
4967,s110017,nomen,None,Ort,l145975,1,core,no,no,no,Standfläche,True,Stand,Fläche,Nomen,None,None,None
502,s40455,nomen,None,natGegenstand,l59250,1,core,no,no,no,Ziegelstein,True,Ziegel,Stein,Nomen,None,None,None

In [27]:
germannet_df.loc[germannet_df.orthForm=="Spielball"]

,synset_id,category,variation,class,lexunit_id,sense,source,namedEntity,artificial,styleMarking,orthForm,compound,modifier,head,modifier_cat,modifier_prop,head_prop,paraphrase
11471,s33157,nomen,None,Geschehen,l45611,1,core,no,no,no,Spielball,True,Spiel,Ball,Nomen,None,None,None
702,s11162,nomen,None,Artefakt,l15471,4,core,no,no,no,Spielball,True,Spiel,Ball,Nomen,None,None,None
1272,s7942,nomen,None,Artefakt,l11337,3,core,no,no,no,Spielball,True,Spiel,Ball,Nomen,None,None,None
14701,s38557,nomen,None,Mensch,l56526,2,core,no,no,no,Spielball,True,Spiel,Ball,Nomen,None,None,None

In [28]:
germannet_df.loc[germannet_df.compound==True].orthForm.value_counts().head(30)

orthForm
Drehscheibe         4
Atmosphäre          4
Rindvieh            4
Großmeister         4
Spielball           4
Zungenschlag        4
Hausarbeit          3
Lebendgeburt        3
Einzelarbeit        3
Notstand            3
Mutterhaus          3
U-Bahn              3
Holzbohrer          3
Diskussionsrunde    3
Kurzform            3
Einzelbild          3
Unterkleid          3
Rechtsordnung       3
Goldkrone           3
Handweberei         3
Storchschnabel      3
Breitseite          3
Wasserschutz        3
Grundton            3
Winterkleid         3
Fuchsschwanz        3
Hintergrund         3
S-Bahn              3
Nachspiel           3
Rückschlag          3
Name: count, dtype: int64

In [29]:
relations_df=read_germanet_xml_rel("/resources/data/GermaNet/GN_V130/GN_V130_XML/gn_relations.xml")
relations_df['from_text']=relations_df['from'].copy()
relations_df['to_text']=relations_df['to'].copy()
relations_df.replace({'from_text':lexid_dict, 'to_text':lexid_dict},inplace=True)
relations_df

,rel_type,name,from,to,inv,from_text,to_text
0,lex_rel,has_pertainym,l763,l22190,None,l763,Emotion
1,lex_rel,has_pertainym,l786,l65372,None,l786,Mimose
2,lex_rel,has_antonym,l800,l756,has_antonym,l800,l756
3,lex_rel,has_pertainym,l967,l22652,None,l967,Erwartung
4,lex_rel,has_pertainym,l1437,l50953,None,l1437,Schriftsteller
...,...,...,...,...,...,...,...
12193,lex_rel,has_content,l16608,l16586,None,Porträtfoto,Porträt
12194,lex_rel,is_part_of,l119281,l66545,None,Rosenblüte,Rose
12195,lex_rel,has_product,l97502,l68335,None,Silbermine,Silber
12196,lex_rel,has_attribute,l9389,l56769,None,Chefsessel,Chef
12197,lex_rel,is_container_for,l120809,l57862,None,Honigtopf,Honig

In [58]:
comp_df=germannet_df.loc[germannet_df.compound==True]
comp_df

,synset_id,category,variation,class,lexunit_id,sense,source,namedEntity,artificial,styleMarking,orthForm,compound,modifier,head,modifier_cat,modifier_prop,head_prop,paraphrase
3,s131243,nomen,None,Attribut,l171637,1,core,no,no,no,Ausreisegenehmigung,True,Ausreise,Genehmigung,Nomen,None,None,None
4,s112235,nomen,None,Attribut,l148797,1,core,no,no,no,Spielniveau,True,Spiel,Niveau,Nomen,None,None,None
5,s67352,nomen,None,Attribut,l93241,1,core,no,no,no,Gefiederfärbung,True,Gefieder,Färbung,Nomen,None,None,None
7,s14294,nomen,None,Attribut,l19889,1,core,no,no,no,Alkoholfahne,True,Alkohol,Fahne,Nomen,None,None,nach Alkohol riechender Atem
9,s13206,nomen,None,Attribut,l18343,1,core,no,no,no,Bierkonsum,True,Bier,Konsum,Nomen,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
848,s40740,nomen,None,natGegenstand,l59598,1,core,no,no,no,Blauquarz,True,blau,Quarz,Adjektiv,None,None,None
849,s40740,nomen,None,natGegenstand,l59599,1,core,no,no,no,Saphirquarz,True,Saphir,Quarz,Nomen,None,None,None
850,s40497,nomen,None,natGegenstand,l59308,1,core,no,no,no,Stein-Eisen-Meteorit,True,Stein Eisen,Meteorit,None,Wortgruppe,None,None
852,s83714,nomen,None,natGegenstand,l112875,1,core,no,no,no,Basaltstein,True,Basalt,Stein,Nomen,None,None,None
853,s40457,nomen,None,natGegenstand,l59253,1,core,no,no,no,Grundstein,True,Grund,Stein,Nomen,None,None,erster gelegter Stein bei einem Bauprojekt

In [62]:
mod_comp_rel_df=comp_df.merge(relations_df[['name','from','to_text','to']],left_on=['lexunit_id','modifier'],right_on=['from','to_text'])
#mod_comp_rel_df.drop(['source','artificial','styleMarking','from','to_text','to'],axis=1,inplace=True)
mod_comp_rel_df

,synset_id,category,variation,class,lexunit_id,sense,source,namedEntity,artificial,styleMarking,...,modifier,head,modifier_cat,modifier_prop,head_prop,paraphrase,name,from,to_text,to
0,s61977,nomen,None,Attribut,l86994,1,core,no,no,no,...,Text,Wüste,Nomen,None,None,None,has_material,l86994,Text,l44676
1,s14381,nomen,None,Attribut,l20010,1,core,no,no,no,...,Page,Kopf,Nomen,None,None,None,is_part_of,l20010,Page,l49504
2,s91270,nomen,None,Attribut,l122353,1,core,no,no,no,...,Zins,Fuß,Nomen,None,None,None,is_measure_of,l122353,Zins,l20213
3,s15891,nomen,None,Attribut,l22058,2,core,no,no,no,...,Haar,Kranz,Nomen,None,None,None,has_material,l22058,Haar,l36049
4,s13339,nomen,None,Attribut,l18506,1,core,no,no,no,...,Lohn,Niveau,Nomen,None,None,None,is_measure_of,l18506,Lohn,l20665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7217,s40753,nomen,None,natGegenstand,l59616,1,core,no,no,no,...,Tiger,Auge,Nomen,None,None,None,is_part_of,l59616,Tiger,l71764
7218,s81052,nomen,None,natGegenstand,l109562,1,core,no,no,no,...,Öl,Sand,Nomen,None,None,None,has_component,l109562,Öl,l59170
7219,s62090,nomen,None,natGegenstand,l87129,1,core,no,no,no,...,Quarz,Sand,Nomen,None,None,None,has_material,l87129,Quarz,l68883
7220,s89903,nomen,None,natGegenstand,l120752,1,core,no,no,no,...,Heimat,Erde,Nomen,None,None,None,has_attribute,l120752,Heimat,l60903
7221,s40661,nomen,None,natGegenstand,l59498,1,core,no,no,no,...,Stein,Kohle,Nomen,None,None,None,has_consistency_of,l59498,Stein,l59224

In [59]:
mod_comp_rel_df['name'].value_counts()

name
is_part_of                         538
has_material                       456
has_part                           406
has_location                       386
has_user                           340
has_active_usage                   339
has_attribute                      329
has_purpose_of_usage               276
has_usage                          271
has_appearance                     266
has_specialization                 227
is_container_for                   211
has_topic                          203
has_function                       201
has_manner_of_functioning          200
has_ingredient                     194
has_owner                          189
has_habitat                        184
has_raw_product                    162
has_content                        158
has_origin                         143
has_time                           130
has_prototypical_place_of_usage    126
has_product                        124
has_occasion                       113
has_prototypical_holder            105
has_other_property                  83
is_location_of                      76
has_relation                        63
is_storage_for                      60
is_member_of                        53
has_member                          47
has_goods                           46
has_result_of_usage                 45
has_component                       43
is_product_of                       41
has_production_method               39
has_no_property                     38
has_consistency_of                  35
is_comparable_to                    35
is_measure_of                       31
has_eponym                          29
has_diet                            28
has_container                       23
is_owner_of                         19
is_prototypical_holder_for          18
is_access_to                        17
is_caused_by                        15
is_ingredient_of                    15
has_construction_method             14
is_diet_of                          11
has_measure                         11
is_cause_for                         8
has_pertainym                        1
has_antonym                          1
Name: count, dtype: int64

In [61]:
comp_df.merge(relations_df[['name','from_text','to']],left_on=['lexunit_id','modifier'],right_on=['to','from_text'])

,synset_id,category,variation,class,lexunit_id,sense,source,namedEntity,artificial,styleMarking,...,compound,modifier,head,modifier_cat,modifier_prop,head_prop,paraphrase,name,from_text,to
0,s46040,nomen,None,Pflanze,l66180,1,core,no,no,no,...,True,Sojabohne,Pflanze,Nomen,None,None,None,is_product_of,Sojabohne,l66180
1,s37540,nomen,None,Mensch,l54236,1,core,no,no,no,...,True,Gast,Geber,Nomen,None,None,None,has_antonym,Gast,l54236

In [29]:
head_comp_rel_df=comp_df.merge(relations_df[['name','from','to_text','to']],left_on=['lexunit_id','head'],right_on=['from','to_text'])
head_comp_rel_df.drop(['source','artificial','styleMarking','from','to_text','to'],axis=1,inplace=True)
head_comp_rel_df

,synset_id,category,variation,class,lexunit_id,sense,namedEntity,orthForm,compound,modifier,head,modifier_cat,modifier_prop,head_prop,paraphrase,name
0,s42564,nomen,None,Artefakt,l62057,1,no,Sandburg,True,Sand,Burg,Nomen,None,None,None,has_appearance
1,s11191,nomen,None,Artefakt,l15514,1,no,Schneemann,True,Schnee,Mann,Nomen,None,None,None,has_appearance
2,s46589,nomen,None,Pflanze,l66827,3,no,Zuckerhut,True,Zucker,Hut,Nomen,None,None,None,has_appearance
3,s76182,nomen,None,Nahrung,l103846,2,no,Zuckerhut,True,Zucker,Hut,Nomen,None,None,None,has_appearance
4,s46297,nomen,None,Nahrung,l66488,1,no,Zimtstange,True,Zimt,Stange,Nomen,None,None,None,has_appearance
5,s15803,nomen,None,Form,l21949,2,no,Schneeball,True,Schnee,Ball,Nomen,None,None,None,has_appearance
6,s118885,nomen,None,Ort,l156722,1,yes,Zuckerhut,True,Zucker,Hut,Nomen,None,None,None,has_appearance

In [33]:
comp_df.merge(relations_df[['name','from_text','to']],left_on=['lexunit_id','head'],right_on=['to','from_text'])

Empty DataFrame
Columns: [synset_id, category, variation, class, lexunit_id, sense, source, namedEntity, artificial, styleMarking, orthForm, compound, modifier, head, modifier_cat, modifier_prop, head_prop, paraphrase, name, from_text, to]
Index: []

[0 rows x 21 columns]

In [34]:
comp_df.merge(relations_df[['name','from_text','to_text','to']],left_on=['modifier','head'],right_on=['from_text','to_text'])

Empty DataFrame
Columns: [synset_id, category, variation, class, lexunit_id, sense, source, namedEntity, artificial, styleMarking, orthForm, compound, modifier, head, modifier_cat, modifier_prop, head_prop, paraphrase, name, from_text, to_text, to]
Index: []

[0 rows x 22 columns]

In [35]:
comp_df.merge(relations_df[['name','from_text','to_text','to']],left_on=['head','modifier'],right_on=['from_text','to_text'])

Empty DataFrame
Columns: [synset_id, category, variation, class, lexunit_id, sense, source, namedEntity, artificial, styleMarking, orthForm, compound, modifier, head, modifier_cat, modifier_prop, head_prop, paraphrase, name, from_text, to_text, to]
Index: []

[0 rows x 22 columns]

In [143]:
with open("/resources/data/GermaNet/GN_V130/GN_V130_DB/GN_V130_database_dump.dump", "r") as f:
    dump_file=f.read().split('\n\n')

for i,row in enumerate(dump_file):
    print(i,len(row))

In [163]:
18

18

In [155]:
dump_file[177]

'\n--\n-- Data for Name: example_table; Type: TABLE DATA; Schema: public; Owner: germanet\n--'

In [153]:
dump_file[178][:1000]

'COPY example_table (id, lex_unit_id, text, frame_type_id) FROM stdin;\n1\t27\teine närrische Freude haben\t\\N\n2\t42\teine knappe Portion\t\\N\n3\t114\tein gewaltiges Erdbeben\t\\N\n4\t121\tschwarze Hoffnungslosigkeit\t\\N\n5\t144\tmir geht es blendend\t\\N\n6\t233\tein Restaurant mit gehobener Küche\t\\N\n7\t291\tein attraktives Angebot\t\\N\n8\t307\tein effektives Unternehmen\t\\N\n9\t341\tfreundliches Wetter\t\\N\n10\t341\teine freundliche Gegend\t\\N\n11\t349\teine bodenlose Frechheit\t\\N\n12\t424\twidriges Wetter\t\\N\n13\t424\twidrige Umstände\t\\N\n14\t574\teine hanebüchene Story\t\\N\n15\t843\tin ausgelassener Stimmung\t\\N\n16\t1067\tmir ist alles egal\t\\N\n17\t1136\tein fröhliches Lied\t\\N\n18\t1137\tein heiteres Lied\t\\N\n19\t1138\tein lustiges Lied\t\\N\n20\t1283\teine bunte Veranstaltung\t\\N\n21\t1445\tein heller Kopf\t\\N\n24\t1520\tSie hörte ihm verträumt zu\t\\N\n25\t1751\tbürgerliche(s) Gesellschaft/Essen/Küche\t\\N\n26\t2600\teine klare Stimme\t\\N\n27\t2612\tIn hellen Augenblicken konnte er sich an alles erinnern\t\\N\n28\t2781\tein aufgewecktes Kind\t\\N\n29\t3262\tvolles Haar\t\\N\n31\t3466\tei'

In [157]:
dump_file[179]

'\n--\n-- Data for Name: compound_table; Type: TABLE DATA; Schema: public; Owner: germanet\n--'

In [183]:
dump_file[171]

'\n--\n-- Data for Name: compound_category_table; Type: TABLE DATA; Schema: public; Owner: germanet\n--'

In [184]:
dump_file[172].split('\n')[0]

'COPY compound_category_table (id, category) FROM stdin;'

In [187]:
172+18

190

In [252]:
dump_file[194].split('\n')[0]

'COPY lex_unit_table (id, synset_id, orth_form, source, named_entity, artificial, style_marking, old_orth_form, old_orth_var, orth_var, comment) FROM stdin;'

In [212]:
trial_df=pd.read_csv(StringIO(dump_file[200]),skiprows=1,header=None,sep='\t',skipfooter=1)
trial_df.columns=['id', 'gn_lex_unit_id', 'wkn_word_entry_id', 'wkn_sense_id', 'wkn_gloss', 'wkn_gloss_edited']
trial_df

/tmp/ipykernel_2896943/3750583006.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  trial_df=pd.read_csv(StringIO(dump_file[200]),skiprows=1,header=None,sep='\t',skipfooter=1)

,id,gn_lex_unit_id,wkn_word_entry_id,wkn_sense_id,wkn_gloss,wkn_gloss_edited
0,28612,6118,72520,0,ohne Bargeld,f
1,28689,74531,65859,2,"auf etwas ankommen: der entscheidende, wichtig...",f
2,28726,6740,62877,0,"umgangssprachlich: tätig, engagiert",f
3,28712,128995,74778,1,mit Absicht,f
4,28845,6935,75536,0,überheblich oder herablassend,f
...,...,...,...,...,...,...
29545,42262,11108,52184,0,"Unterhaltungselektronik: Ein Gerät, um Radio- ...",f
29546,42638,103712,53110,1,eine von zwei oder mehr Möglichkeiten,f
29547,34918,45366,17286,0,"literarischer Text, der zur Aufführung auf ein...",f
29548,40230,145945,49225,2,Sport: eine Übung in einer bestimmten Disziplin,f
29549,53171,89422,137357,4,Hilfsverb haben: mit dem Fuß oder Knie einen H...,f

In [257]:
lex_df=pd.read_csv(StringIO(dump_file[194]),skiprows=1,header=None,sep='\t',skipfooter=1,engine='python')
lex_df.columns=['lex_id', 'synset_id', 'orth_form', 'source', 'named_entity', 'artificial', 'style_marking', 'old_orth_form', 'old_orth_var', 'orth_var', 'comment']
lex_df

,lex_id,synset_id,orth_form,source,named_entity,artificial,style_marking,old_orth_form,old_orth_var,orth_var,comment
0,136210,102534,Vorführgerät,core,f,f,f,\N,\N,\N,\N
1,136212,102534,Vorführmodell,core,f,f,f,\N,\N,\N,\N
2,136216,102536,Lehramtsstudent,core,f,f,f,\N,\N,\N,\N
3,136217,102536,Lehramtsstudentin,core,f,f,f,\N,\N,\N,\N
4,136218,102537,Leitgewebe,core,f,f,f,\N,\N,\N,\N
...,...,...,...,...,...,...,...,...,...,...,...
164809,136209,102533,Lebenschance,core,f,f,f,\N,\N,\N,\N
164810,136211,24312,Lebensmittelbranche,core,f,f,f,\N,\N,\N,\N
164811,136213,102535,Lebensmittelvorrat,core,f,f,f,\N,\N,\N,\N
164812,136214,34095,Ledige,core,f,f,f,\N,\N,\N,\N
164813,136215,34094,Lediger,core,f,f,f,\N,\N,\N,\N

In [258]:
lex_df.loc[lex_df.lex_id==6118]

,lex_id,synset_id,orth_form,source,named_entity,artificial,style_marking,old_orth_form,old_orth_var,orth_var,comment
115903,6118,4157,bargeldlos,core,f,f,f,\N,\N,\N,\N

In [262]:
combined_df=pd.merge(lex_df,trial_df,left_on='lex_id',right_on='gn_lex_unit_id')

In [266]:
what_df=pd.merge(combined_df,xml_df,left_on='orth_form',right_on='title')
what_df

,lex_id,synset_id,orth_form,source,named_entity,artificial,style_marking,old_orth_form,old_orth_var,orth_var,comment,id_x,gn_lex_unit_id,wkn_word_entry_id,wkn_sense_id,wkn_gloss,wkn_gloss_edited,title,id_y,text
0,136285,102586,hässlich,core,f,f,f,häßlich,\N,\N,\N,56289,136285,100265,2,"verletzend, gemein",f,hässlich,153371,== hässlich ({{Sprache|Deutsch}}) ==\n=== {{Wo...
1,2847,1842,hässlich,core,f,f,f,häßlich,\N,\N,\N,50904,2847,100265,0,unschön aussehend,f,hässlich,153371,== hässlich ({{Sprache|Deutsch}}) ==\n=== {{Wo...
2,136311,102607,diskret,core,f,f,f,\N,\N,\N,\N,28943,136311,85504,0,etwas geheim haltend; vertraulich,f,diskret,7352,== diskret ({{Sprache|Deutsch}}) ==\n=== {{Wor...
3,128274,96126,diskret,core,f,f,f,\N,\N,\N,\N,56068,128274,85504,1,"Mathematik, nicht steigerbar: getrennt, keine ...",f,diskret,7352,== diskret ({{Sprache|Deutsch}}) ==\n=== {{Wor...
4,128274,96126,diskret,core,f,f,f,\N,\N,\N,\N,56069,128274,85504,2,"Physik, nicht kontinuierlich: einzeln, nicht z...",f,diskret,7352,== diskret ({{Sprache|Deutsch}}) ==\n=== {{Wor...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29523,132226,99401,klassisch,core,f,f,f,\N,\N,\N,\N,29858,132226,104942,0,Geschichte: die antike Klassik betreffend,f,klassisch,153371,== klassisch ({{Sprache|Deutsch}}) ==\n=== {{W...
29524,132226,99401,klassisch,core,f,f,f,\N,\N,\N,\N,29859,132226,104942,1,"Musik, Dichtkunst: stilistische Merkmale der K...",f,klassisch,153371,== klassisch ({{Sprache|Deutsch}}) ==\n=== {{W...
29525,63160,100774,Prärie,core,f,f,f,\N,\N,\N,\N,37224,63160,43208,0,Graslandschaft in Nordamerika,f,Prärie,5327,== Prärie ({{Sprache|Deutsch}}) ==\n=== {{Wort...
29526,22876,16438,Ereignis,core,f,f,f,\N,\N,\N,\N,38677,22876,20266,0,ein - meist bedeutsames - Geschehen oder Erlebnis,f,Ereignis,190722,== Ereignis ({{Sprache|Deutsch}}) ==\n=== {{Wo...
29527,12313,8737,Skilift,core,f,f,f,\N,\N,Schilift,\N,39827,12313,48320,0,"Wintersport: eine Seilbahn, mit der Skifahrer ...",f,Skilift,720,== Skilift ({{Sprache|Deutsch}}) ==\n=== {{Wor...

In [271]:
what_df.loc[what_df.orth_form=='diskret']

,lex_id,synset_id,orth_form,source,named_entity,artificial,style_marking,old_orth_form,old_orth_var,orth_var,comment,id_x,gn_lex_unit_id,wkn_word_entry_id,wkn_sense_id,wkn_gloss,wkn_gloss_edited,title,id_y,text
2,136311,102607,diskret,core,f,f,f,\N,\N,\N,\N,28943,136311,85504,0,etwas geheim haltend; vertraulich,f,diskret,7352,== diskret ({{Sprache|Deutsch}}) ==\n=== {{Wor...
3,128274,96126,diskret,core,f,f,f,\N,\N,\N,\N,56068,128274,85504,1,"Mathematik, nicht steigerbar: getrennt, keine ...",f,diskret,7352,== diskret ({{Sprache|Deutsch}}) ==\n=== {{Wor...
4,128274,96126,diskret,core,f,f,f,\N,\N,\N,\N,56069,128274,85504,2,"Physik, nicht kontinuierlich: einzeln, nicht z...",f,diskret,7352,== diskret ({{Sprache|Deutsch}}) ==\n=== {{Wor...

In [200]:
for i in range(172,214,2):
    print(i)
    print(dump_file[i].split('\n')[0])
    print(pd.read_csv(StringIO(dump_file[i]),skiprows=1,header=None,sep='\t'))

172
COPY compound_category_table (id, category) FROM stdin;
    0               1
0   0        Adjektiv
1   1           Nomen
2   2            Verb
3   3          Adverb
4   4     Präposition
5   5        Partikel
6   6        Pronomen
7   7          Präfix
8   8  Verbalpartikel
9  \.             NaN
174
COPY compound_property_table (id, property) FROM stdin;
     0                   1
0    0           Abkürzung
1    1            Affixoid
2    2           Fremdwort
3    3              Konfix
4    4     opaques Morphem
5    5   virtuelle Bildung
6    6          Wortgruppe
7    7          Konversion
8    8           Eigenname
9    9  gebundenes Morphem
10  10      freies Morphem
11  \.                 NaN
176
COPY ewn_rel_table (id, name) FROM stdin;
     0                  1
0    1            synonym
1    4             causes
2    3       near_synonym
3    5               role
4   13           involved
5   15  xpos_near_synonym
6    7        has_hyponym
7    8        has_holonym
8    9        has_meronym
9   12        be_in_state
10  10       has_subevent
11   6     is_subevent_of
12   0       is_caused_by
13   2       has_hypernym
14  \.                NaN
178
COPY example_table (id, lex_unit_id, text, frame_type_id) FROM stdin;
           0         1                                                  2    3
0          1      27.0                        eine närrische Freude haben   \N
1          2      42.0                                eine knappe Portion   \N
2          3     114.0                            ein gewaltiges Erdbeben   \N
3          4     121.0                        schwarze Hoffnungslosigkeit   \N
4          5     144.0                               mir geht es blendend   \N
...      ...       ...                                                ...  ...
20665  23255  169172.0                          Sie danisierten Grönland.    2
20666  23256  169191.0             Die Sängerin tremulierte herzbewegend.    0
20667  23257  168959.0                     Sie schampunierte den Teppich.    2
20668  23258  170100.0  Das Fahrzeug wurde mit einem Rußfilter nachger...   46
20669     \.       NaN                                                NaN  NaN

[20670 rows x 4 columns]
180
COPY compound_table (id, comp_property, comp_lex_unit_id, mod1_property, mod1_category, modifier1, mod1_lex_unit_id, mod2_category, modifier2, mod2_lex_unit_id, head_property, head, head_lex_unit_id, mod2_property, mod1_lex_unit_id2, mod1_lex_unit_id3, mod2_lex_unit_id2, mod2_lex_unit_id3) FROM stdin;

/tmp/ipykernel_2896943/867992259.py:4: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  print(pd.read_csv(StringIO(dump_file[i]),skiprows=1,header=None,sep='\t'))
/tmp/ipykernel_2896943/867992259.py:4: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  print(pd.read_csv(StringIO(dump_file[i]),skiprows=1,header=None,sep='\t'))

           0    1         2    3    4           5    6    7      8    9    10  \
0      222840   \N  152071.0    1   \N       haupt   \N   \N     \N   \N   \N
1      222870   \N  152105.0    8    1      Stalin   \N   \N     \N   \N   \N
2      222909   \N  152149.0   \N    1     Fahrrad   \N   \N     \N   \N   \N
3      222913   \N  152153.0   \N    1    Finanzen   \N   \N     \N   \N   \N
4      222918   \N  152159.0   \N    1       Armut   \N   \N     \N   \N   \N
...       ...  ...       ...  ...  ...         ...  ...  ...    ...  ...  ...
84744  222784   \N  152008.0   \N    1        Reis   \N   \N     \N   \N   \N
84745  222812   \N  152036.0   \N    2      taufen   \N    1  Taufe   \N   \N
84746  222815   \N  152043.0   \N    1  Stabilität   \N   \N     \N   \N   \N
84747  222816   \N  152046.0   \N    1        Kino   \N   \N     \N   \N   \N
84748      \.  NaN       NaN  NaN  NaN         NaN  NaN  NaN    NaN  NaN  NaN

                11   12   13   14   15   16   17
0             Land   \N   \N   \N   \N   \N   \N
1             Zeit   \N   \N   \N   \N   \N   \N
2         Mitnahme   \N   \N   \N   \N   \N   \N
3      Departement   \N   \N   \N   \N   \N   \N
4            Ideal   \N   \N   \N   \N   \N   \N
...            ...  ...  ...  ...  ...  ...  ...
84744        Sorte   \N   \N   \N   \N   \N   \N
84745     Bewerber   \N   \N   \N   \N   \N   \N
84746       Gründe   \N   \N   \N   \N   \N   \N
84747      Sterben   \N   \N   \N   \N   \N   \N
84748          NaN  NaN  NaN  NaN  NaN  NaN  NaN

[84749 rows x 18 columns]
182
COPY con_rel_table (id, rel_type_id, from_synset_id, to_synset_id) FROM stdin;
             0    1         2        3
0         1066  0.0    1031.0   1027.0
1         1199  0.0    1158.0   1156.0
2         1567  0.0    1515.0   1455.0
3         1592  0.0    1540.0   1527.0
4         1617  0.0    1565.0   1559.0
...        ...  ...       ...      ...
141770  164755  0.0  132299.0  36006.0
141771  165013  0.0  132537.0  89136.0
141772  165622  0.0  133080.0  37426.0
141773  165716  0.0  133166.0  38155.0
141774      \.  NaN       NaN      NaN

[141775 rows x 4 columns]
184
COPY con_rel_type_table (id, name, direction, inverse, transitive) FROM stdin;
    0                      1       2                      3    4
0   7     has_member_meronym  revert     has_member_holonym    f
1   9  has_substance_meronym  revert  has_substance_holonym    f
2   8    has_portion_meronym  revert    has_portion_holonym    f
3   6  has_component_meronym  revert  has_component_holonym    f
4   4                entails  revert         is_entailed_by    f
5   5                 causes     one                     \N    f
6   1          is_related_to    both          is_related_to    f
7   0           has_hypernym  revert            has_hyponym    t
8  \.                    NaN     NaN                    NaN  NaN
186
COPY ili_pwn20_synonym_table (id, ili_id, pwn20_synonym) FROM stdin;
           0        1                   2
0          0      5.0               serve
1          1      4.0          recompense
2          2      4.0              repair
3          3      4.0           indemnify
4          4      3.0             snap at
...      ...      ...                 ...
37990  83436  73756.0  rhinolaryngologist
37991  83437  73759.0               kitty
37992  83438  73760.0            promoter
37993  83439  73760.0          impresario
37994     \.      NaN                 NaN

[37995 rows x 3 columns]
188
COPY ili_table (id, gn_lex_unit_id, gn_old_sense, ewn_relation, pwn_word, pwn20_id, pwn30_id, source, pwn20_paraphrase) FROM stdin;
           0        1    2    3                    4                 5  \
0       5987  65378.0    0  1.0               Myrtus  ENG20-11582102-n
1      73661  23952.0   \N  1.0           pilgrimage  ENG20-00298020-n
2      73673   9221.0   \N  1.0                 bill  ENG20-06376031-n
3      18161  46486.0   \N  1.0               factor  ENG20-12827796-n
4      73654  39114.0   \N  3.0             estimate  ENG20-06366628-n
...      ...      ...  ...  ...                  ...               ...
28562   3239  54371.0    0  1.0              convict  ENG20-09326003-n
28563  25851  54372.0   \N  1.0              convict  ENG20-09326003-n
28564  23983  38467.0   \N  1.0  veterinary medicine  ENG20-05705862-n
28565   2508  22876.0    0  1.0                event  ENG20-00025950-n
28566     \.      NaN  NaN  NaN                  NaN               NaN

                      6             7  \
0      ENG30-12330336-n       initial
1      ENG30-00311687-n   Erweiterung
2      ENG30-06793426-n       initial
3      ENG30-13593219-n   Erweiterung
4      ENG30-06783598-n   Erweiterung
...                 ...           ...
28562  ENG30-09962966-n       initial
28563  ENG30-09962966-n  Erweiterung2
28564  ENG30-06065423-n  Erweiterung2
28565  ENG30-00029378-n       initial
28566               NaN           NaN

                                                       8
0                            type genus of the Myrtaceae
1                            a journey to a sacred place
2      a sign posted in a public place as an advertis...
3      any of the numbers (or symbols) that form a pr...
4      a statement indicating the likely cost of some...
...                                                  ...
28562    a person serving a sentence in a jail or prison
28563    a person serving a sentence in a jail or prison
28564  the branch of medicine that deals with the dia...
28565   something that happens at a given place and time
28566                                                NaN

[28567 rows x 9 columns]
190
COPY lex_rel_table (id, rel_type_id, from_lex_unit_id, to_lex_unit_id) FROM stdin;
           0     1         2         3
0      27533  11.0  140851.0   41626.0
1      24471  45.0  141105.0   70708.0
2      24684  17.0  141352.0   40460.0
3      28411  50.0   94316.0   86821.0
4      24194  34.0  118318.0   68470.0
...      ...   ...       ...       ...
12194  22799   1.0  132066.0   46973.0
12195  22515   1.0  134326.0  116871.0
12196  22518   1.0  134462.0   37724.0
12197  26095  44.0  124673.0   36101.0
12198     \.   NaN       NaN       NaN

[12199 rows x 4 columns]
192
COPY lex_rel_type_table (id, name, direction, inverse) FROM stdin;
     0                                1     2            3
0    4                   has_participle   one           \N
1    0                      has_antonym  both  has_antonym
2    1                    has_pertainym   one           \N
3    5                 has_active_usage   one           \N
4    6                     has_occasion   one           \N
5    7                    has_attribute   one           \N
6    8                   has_appearance   one           \N
7    9          has_construction_method   one           \N
8   10                    has_container   one           \N
9   11                 is_container_for   one           \N
10  12               has_consistency_of   one           \N
11  13                    has_component   one           \N
12  14                        has_owner   one           \N
13  16                     has_function   one           \N
14  17        has_manner_of_functioning   one           \N
15  18                       has_origin   one           \N
16  19            has_production_method   one           \N
17  20                      has_content   one           \N
18  21                  has_no_property   one           \N
19  22                      has_habitat   one           \N
20  23                     has_location   one           \N
21  24                   is_location_of   one           \N
22  25                      has_measure   one           \N
23  26                    is_measure_of   one           \N
24  27                     has_material   one           \N
25  28                       has_member   one           \N
26  29                     is_member_of   one           \N
27  30                         has_diet   one           \N
28  31                       is_diet_of   one           \N
29  32                       has_eponym   one           \N
30  33                         has_user   one           \N
31  34                      has_product   one           \N
32  35                    is_product_of   one           \N
33  39                     has_relation   one           \N
34  40                  has_raw_product   one           \N
35  41               has_other_property   one           \N
36  42                   is_storage_for   one           \N
37  43               has_specialization   one           \N
38  44                         has_part   one           \N
39  45                       is_part_of   one           \N
40  46                        has_topic   one           \N
41  47                     is_caused_by   one           \N
42  48                     is_cause_for   one           \N
43  49                 is_comparable_to   one           \N
44  50                        has_usage   one           \N
45  51              has_result_of_usage   one           \N
46  52             has_purpose_of_usage   one           \N
47  53                        has_goods   one           \N
48  54                         has_time   one           \N
49  55                     is_access_to   one           \N
50  56                   has_ingredient   one           \N
51  57                 is_ingredient_of   one           \N
52  15                      is_owner_of   one           \N
53  38  has_prototypical_place_of_usage   one           \N
54  36          has_prototypical_holder   one           \N
55  37       is_prototypical_holder_for   one           \N
56  \.                              NaN   NaN          NaN
194
COPY lex_unit_table (id, synset_id, orth_form, source, named_entity, artificial, style_marking, old_orth_form, old_orth_var, orth_var, comment) FROM stdin;

/tmp/ipykernel_2896943/867992259.py:4: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  print(pd.read_csv(StringIO(dump_file[i]),skiprows=1,header=None,sep='\t'))

            0         1                    2     3    4    5    6    7    8   \
0       136210  102534.0         Vorführgerät  core    f    f    f   \N   \N
1       136212  102534.0        Vorführmodell  core    f    f    f   \N   \N
2       136216  102536.0      Lehramtsstudent  core    f    f    f   \N   \N
3       136217  102536.0    Lehramtsstudentin  core    f    f    f   \N   \N
4       136218  102537.0           Leitgewebe  core    f    f    f   \N   \N
...        ...       ...                  ...   ...  ...  ...  ...  ...  ...
164810  136211   24312.0  Lebensmittelbranche  core    f    f    f   \N   \N
164811  136213  102535.0   Lebensmittelvorrat  core    f    f    f   \N   \N
164812  136214   34095.0               Ledige  core    f    f    f   \N   \N
164813  136215   34094.0              Lediger  core    f    f    f   \N   \N
164814      \.       NaN                  NaN   NaN  NaN  NaN  NaN  NaN  NaN

         9    10
0        \N   \N
1        \N   \N
2        \N   \N
3        \N   \N
4        \N   \N
...     ...  ...
164810   \N   \N
164811   \N   \N
164812   \N   \N
164813   \N   \N
164814  NaN  NaN

[164815 rows x 11 columns]
196
COPY log_table (id, modifier, mod_time, modified_cell, modified_object_id, old_value, new_value) FROM stdin;
    0
0  \.
198
COPY synset_table (id, word_class_id, word_category_id, paraphrase, comment) FROM stdin;
             0     1    2                                                  3  \
0       121499  23.0  1.0                                                 \N
1       103294  24.0  1.0                                                 \N
2        81339  22.0  2.0                                                 \N
3         2026   6.0  0.0                                                 \N
4       122515   7.0  1.0                                                 \N
...        ...   ...  ...                                                ...
128096   92077   8.0  1.0                                                 \N
128097   59315  36.0  2.0       etwas Altes beenden und etwas Neues beginnen
128098   55290  22.0  2.0                                                 \N
128099   22262  20.0  1.0  der Prozess des Einzäunen eines Grundstücks zu...
128100      \.   NaN  NaN                                                NaN

          4
0        \N
1        \N
2        \N
3        \N
4        \N
...     ...
128096   \N
128097   \N
128098   \N
128099   \N
128100  NaN

[128101 rows x 5 columns]
200
COPY wkn_sense_table (id, gn_lex_unit_id, wkn_word_entry_id, wkn_sense_id, wkn_gloss, wkn_gloss_edited) FROM stdin;
           0         1         2    3  \
0      28612    6118.0   72520.0  0.0
1      28689   74531.0   65859.0  2.0
2      28726    6740.0   62877.0  0.0
3      28712  128995.0   74778.0  1.0
4      28845    6935.0   75536.0  0.0
...      ...       ...       ...  ...
29546  42638  103712.0   53110.0  1.0
29547  34918   45366.0   17286.0  0.0
29548  40230  145945.0   49225.0  2.0
29549  53171   89422.0  137357.0  4.0
29550     \.       NaN       NaN  NaN

                                                       4    5
0                                           ohne Bargeld    f
1      auf etwas ankommen: der entscheidende, wichtig...    f
2                    umgangssprachlich: tätig, engagiert    f
3                                            mit Absicht    f
4                          überheblich oder herablassend    f
...                                                  ...  ...
29546              eine von zwei oder mehr Möglichkeiten    f
29547  literarischer Text, der zur Aufführung auf ein...    f
29548    Sport: eine Übung in einer bestimmten Disziplin    f
29549  Hilfsverb haben: mit dem Fuß oder Knie einen H...    f
29550                                                NaN  NaN

[29551 rows x 6 columns]
202
COPY frame_table (id, lex_unit_id, frame_type_id) FROM stdin;
           0         1     2
0          2   73263.0   0.0
1          4   73267.0   7.0
2          5   73270.0   2.0
3          6   73271.0   2.0
4          8   73272.0   2.0
...      ...       ...   ...
20558  24358  169172.0   2.0
20559  24359  169191.0   0.0
20560  24360  168959.0   2.0
20561  24361  170100.0  46.0
20562     \.       NaN   NaN

[20563 rows x 3 columns]
204
COPY frame_type_table (id, frame) FROM stdin;
       0          1
0      0         NN
1      1         NE
2      2      NN.AN
3      3      NN.BT
4      4      NN.BL
..   ...        ...
207  210   NN.Bs.DS
208  195   NN.PP.Ds
209  263  NN.Bl.FSo
210  196   NN.PP.Fs
211   \.        NaN

[212 rows x 2 columns]
206
COPY id_generation_table (generated_key, generated_value) FROM stdin;
                       0         1
0            compound_id   77486.0
1             example_id   23259.0
2          wiktionary_id   56519.0
3                 ili_id   36605.0
4               frame_id   24362.0
5             lex_rel_id   30664.0
6   ili_pwn20_synonym_id   42683.0
7                 log_id  441202.0
8              synset_id  133578.0
9            lex_unit_id  174568.0
10            con_rel_id  166229.0
11                    \.       NaN
208
COPY log_cell_table (id, table_name, cell_name) FROM stdin;
     0                        1                  2
0    0           lex_unit_table                all
1    1           lex_unit_table          orth_form
2    2           lex_unit_table           orth_var
3    3           lex_unit_table      old_orth_form
4    4           lex_unit_table       old_orth_var
5    5           lex_unit_table             source
6    6           lex_unit_table       named_entity
7    7           lex_unit_table         artificial
8    8           lex_unit_table      style_marking
9    9             synset_table                all
10  10             synset_table   word_category_id
11  11             synset_table      word_class_id
12  12             synset_table         paraphrase
13  13             synset_table            comment
14  14            lex_rel_table                all
15  15            con_rel_table                all
16  16              frame_table                all
17  17              frame_table      frame_type_id
18  18            example_table                all
19  19            example_table      frame_type_id
20  20            example_table               text
21  21           lex_unit_table            comment
22  22          wkn_sense_table                all
23  23          wkn_sense_table     gn_lex_unit_id
24  24          wkn_sense_table  wkn_word_entry_id
25  25          wkn_sense_table       wkn_sense_id
26  26          wkn_sense_table          wkn_gloss
27  27          wkn_sense_table   wkn_gloss_edited
28  28                ili_table                all
29  29                ili_table     gn_lex_unit_id
30  30                ili_table       ewn_relation
31  31                ili_table           pwn_word
32  32                ili_table           pwn20_id
33  33                ili_table           pwn30_id
34  34                ili_table             source
35  35  ili_pwn20_synonym_table                all
36  36           compound_table                all
37  39           compound_table          modifier1
38  40           compound_table         mod1_lu_id
39  42           compound_table          modifier2
40  43           compound_table         mod2_lu_id
41  45           compound_table               head
42  46           compound_table         head_lu_id
43  38           compound_table      mod1_category
44  41           compound_table      mod2_category
45  44           compound_table      head_property
46  48           compound_table          splitting
47  37           compound_table      mod1_property
48  49           compound_table      mod2_property
49  \.                      NaN                NaN
210
COPY word_category_table (id, word_category) FROM stdin;
    0       1
0   0     adj
1   1   nomen
2   2  verben
3  \.     NaN
212
COPY word_class_table (id, word_class) FROM stdin;
     0                1
0    0        Allgemein
1    1         Bewegung
2    2          Gefuehl
3    3            Geist
4    4     Gesellschaft
5    5          Koerper
6    6            Menge
7    7     natPhaenomen
8    8              Ort
9    9         Pertonym
10  10       Perzeption
11  11         privativ
12  12         Relation
13  13         Substanz
14  14        Verhalten
15  15             Zeit
16  16         Artefakt
17  17         Attribut
18  18           Besitz
19  19             Form
20  20        Geschehen
21  21           Gruppe
22  22        Kognition
23  23    Kommunikation
24  24           Mensch
25  25            Motiv
26  26          Nahrung
27  27    natGegenstand
28  28          Pflanze
29  29             Tier
30  30             Tops
31  31  Koerperfunktion
32  32       Konkurrenz
33  33          Kontakt
34  34         Lokation
35  35       Schoepfung
36  36     Veraenderung
37  37        Verbrauch
38  \.              NaN

In [198]:
compound_category_table=
#compound_category_table.columns=['comp_id','comp_cat']
compound_category_table

     0                1
0    0        Allgemein
1    1         Bewegung
2    2          Gefuehl
3    3            Geist
4    4     Gesellschaft
5    5          Koerper
6    6            Menge
7    7     natPhaenomen
8    8              Ort
9    9         Pertonym
10  10       Perzeption
11  11         privativ
12  12         Relation
13  13         Substanz
14  14        Verhalten
15  15             Zeit
16  16         Artefakt
17  17         Attribut
18  18           Besitz
19  19             Form
20  20        Geschehen
21  21           Gruppe
22  22        Kognition
23  23    Kommunikation
24  24           Mensch
25  25            Motiv
26  26          Nahrung
27  27    natGegenstand
28  28          Pflanze
29  29             Tier
30  30             Tops
31  31  Koerperfunktion
32  32       Konkurrenz
33  33          Kontakt
34  34         Lokation
35  35       Schoepfung
36  36     Veraenderung
37  37        Verbrauch
38  \.              NaN

In [36]:
import bz2
from io import StringIO,BytesIO

In [41]:
cur_path='dewiktionary-20240120-pages-articles.xml.bz2'

In [202]:
with bz2.open(cur_path, "rb") as bz_file:
    xml_data=bz_file.read()
xml_df = pd.read_xml(BytesIO(xml_data),
         iterparse = {"page": ["id","title", "text"]})

In [205]:
xml_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1108994 entries, 166 to 1244386
Data columns (total 3 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   title   1108994 non-null  object
 1   id      1108994 non-null  int64
 2   text    1108994 non-null  object
dtypes: int64(1), object(2)
memory usage: 33.8+ MB

In [204]:
xml_df.loc[xml_df.id==72520]

Empty DataFrame
Columns: [title, id, text]
Index: []

element_list = []
for event, element in etree.iterparse(trial_xml):
    element_list.append(etree.tostring(element))
    element.clear()
element_list[:10]

In [203]:
xml_df=xml_df.loc[xml_df.title.str.contains(':')==False]
xml_df

,title,id,text
166,Hallo,216634,"{{Siehe auch|[[hallo]], [[halló]]}}\n== Hallo ..."
182,ordo,84147,{{Siehe auch|[[Ordo]]}}\n== ōrdo ({{Sprache|La...
183,familia,153371,{{Siehe auch|[[família]]}}\n== familia ({{Spra...
184,species,153371,{{Siehe auch|[[Species]]}}\n== species ({{Spra...
185,classis,720,{{Siehe auch|[[Classis]]}}\n== classis ({{Spra...
...,...,...,...
1244382,Vogelbeckensaurier,43509,== Vogelbeckensaurier ({{Sprache|Deutsch}}) ==...
1244383,Echsenbeckensaurier,43509,== Echsenbeckensaurier ({{Sprache|Deutsch}}) =...
1244384,Βηθλέεμ,7006,== Βηθλέεμ ({{Sprache|Altgriechisch}}) ==\n===...
1244385,Appalachia,43509,== Appalachia ({{Sprache|Deutsch}}) ==\n=== {{...
1244386,Laramidia,43509,== Laramidia ({{Sprache|Deutsch}}) ==\n=== {{W...

In [45]:
noun_df=xml_df.loc[xml_df.text.str.contains('Substantiv\|Deutsch')]
noun_df.text=noun_df.text.str.replace('(\{\{Siehe auch\|.*\}\})(\n\n)','\\1\n',regex=True)
noun_df

/tmp/ipykernel_2613092/4219137435.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  noun_df.text=noun_df.text.str.replace('(\{\{Siehe auch\|.*\}\})(\n\n)','\\1\n',regex=True)

,title,text
166,Hallo,"{{Siehe auch|[[hallo]], [[halló]]}}\n== Hallo ..."
186,Subfamilia,== Subfamilia ({{Sprache|Deutsch}}) ==\n=== {{...
189,Subregnum,== Subregnum ({{Sprache|Deutsch}}) ==\n=== {{W...
190,Subdivisio,== Subdivisio ({{Sprache|Deutsch}}) ==\n=== {{...
191,Phylum,{{Siehe auch|[[phylum]]}}\n== Phylum ({{Sprach...
...,...,...
1244381,Viridarium,== Viridarium ({{Sprache|Deutsch}}) ==\n=== {{...
1244382,Vogelbeckensaurier,== Vogelbeckensaurier ({{Sprache|Deutsch}}) ==...
1244383,Echsenbeckensaurier,== Echsenbeckensaurier ({{Sprache|Deutsch}}) =...
1244385,Appalachia,== Appalachia ({{Sprache|Deutsch}}) ==\n=== {{...
1244386,Laramidia,== Laramidia ({{Sprache|Deutsch}}) ==\n=== {{W...

In [46]:
noun_df.loc[noun_df.text.str.count('=== {{Wortart\|.* ===')>1]

                 title                                               text
205              April  {{Siehe auch|[[april]], [[apríl]]}}\n== April ...
206                Mai  {{Siehe auch|[[mai]], [[MAI]], [[maí]]}}\n== M...
209             August  {{Siehe auch|[[august]]}}\n== August ({{Sprach...
210          September  {{Siehe auch|[[september]]}}\n== September ({{...
212           November  {{Siehe auch|[[november]], [[nóvember]]}}\n== ...
...                ...                                                ...
1241878       Bostoner  == Bostoner ({{Sprache|Deutsch}}) ==\n=== {{Wo...
1242767  Haftbedingung  == Haftbedingung ({{Sprache|Deutsch}}) ==\n===...
1242791       Bergbach  == Bergbach ({{Sprache|Deutsch}}) ==\n=== {{Wo...
1242901       Afrasiab  == Afrasiab ({{Sprache|Deutsch}}) ==\n=== {{Wo...
1243347           Sima  == Sima ({{Sprache|Deutsch}}) ==\n=== {{Wortar...

[4627 rows x 2 columns]

In [47]:
noun_df.loc[noun_df.title.str.count(" ")>0]

,title,text
2224,Geospiza conirostris,== Geospiza conirostris ({{Sprache|Deutsch}}) ...
2449,Otto Normalverbraucher,{{Siehe auch|[[Ottonormalverbraucher]]}}\n== O...
2698,Vereinigte Staaten,== Vereinigte Staaten ({{Sprache|Deutsch}}) ==...
2972,Gewinn- und Verlustrechnung,{{Siehe auch|[[Gewinn-und-Verlust-Rechnung]]}}...
3192,Delirium tremens,{{Siehe auch|[[delirium tremens]]}}\n== Deliri...
...,...,...
1241096,Nervus Rerum,== Nervus Rerum ({{Sprache|Deutsch}}) ==\n=== ...
1241211,Brand Manager,== Brand Manager ({{Sprache|Deutsch}}) ==\n===...
1241276,Trade Marketing Manager,== Trade Marketing Manager ({{Sprache|Deutsch}...
1241511,Coney Island,== Coney Island ({{Sprache|Deutsch}}) ==\n=== ...
1242046,Catskill Mountains,== Catskill Mountains ({{Sprache|Deutsch}}) ==...

In [49]:
noun_df.loc[noun_df.text.str.count('== .* \{\{Wortart\|.*\|Deutsch\}\} ==')>1].sample(20)

              title                                               text
91640        Fabian  == Fabian ({{Sprache|Deutsch}}) ==\n=== {{Wort...
3413        Jupiter  == Jupiter ({{Sprache|Deutsch}}) ==\n=== {{Wor...
40592         Amber  == Amber ({{Sprache|Deutsch}}) ==\n=== {{Worta...
14511        Walter  == Walter ({{Sprache|Deutsch}}) ==\n=== {{Wort...
4528         Aachen  == Aachen ({{Sprache|Deutsch}}) ==\n=== {{Wort...
126527  Neunkirchen  == Neunkirchen ({{Sprache|Deutsch}}) ==\n=== {...
437880        Micha  == Micha ({{Sprache|Deutsch}}) ==\n=== {{Worta...
99062          Lodz  {{Siehe auch|[[łódź]], [[Łódź]]}}\n== Lodz ({{...
84282         Böhme  == Böhme ({{Sprache|Deutsch}}) ==\n=== {{Worta...
17640         Heide  {{Siehe auch|[[-heide]]}}\n== Heide ({{Sprache...
614435         Dahl  == Dahl ({{Sprache|Deutsch}}) ==\n=== {{Wortar...
783         Abraham  {{Siehe auch|[[Ábraham]]}}\n== Abraham ({{Spra...
10051       Nepomuk  == Nepomuk ({{Sprache|Deutsch}}) ==\n=== {{Wor...
120208     Horstmar  == Horstmar ({{Sprache|Deutsch}}) ==\n=== {{Wo...
3259         Albert  {{Siehe auch|[[albert]]}}\n== Albert ({{Sprach...
1995          Engel  {{Siehe auch|[[engel]]}}\n== Engel ({{Sprache|...
25758      Suriname  == Suriname ({{Sprache|Deutsch}}) ==\n=== {{Wo...
99951        Lublin  == Lublin ({{Sprache|Deutsch}}) ==\n=== {{Wort...
2313            Aar  {{Siehe auch|[[aar]], [[AAR]]}}\n{{Wort der Wo...
6016            Kai  {{Siehe auch|[[kai]], [[KAI]]}}\n== Kai ({{Spr...

In [56]:
noun_df.loc[noun_df.text.str.count('== .* \({{Sprache\|.* ==')>1].sample(20)

                    title                                               text
75192              Marion  == Marion ({{Sprache|Deutsch}}) ==\n=== {{Wort...
382112             Recife  == Recife ({{Sprache|Deutsch}}) ==\n=== {{Wort...
21141           Darmstadt  == Darmstadt ({{Sprache|Deutsch}}) ==\n=== {{W...
20489            Mannheim  == Mannheim ({{Sprache|Deutsch}}) ==\n=== {{Wo...
40425                 Ada  {{Siehe auch|[[ada]], [[Adą]], [[āda]], [[ādā]...
12851               Baldo  == Baldo ({{Sprache|Deutsch}}) ==\n=== {{Worta...
40616              Gloria  {{Siehe auch|[[gloria]], [[glòria]]}}\n== Glor...
230640              Ajmer  == Ajmer ({{Sprache|Deutsch}}) ==\n=== {{Worta...
121793       Antananarivo  == Antananarivo ({{Sprache|Deutsch}}) ==\n=== ...
122148  Santiago de Chile  == Santiago de Chile ({{Sprache|Deutsch}}) ==\...
1813                    G  {{Siehe auch|[[g]], [[ġ]], [[Ġ]], [[ĝ]], [[Ĝ]]...
232776           Amarillo  {{Siehe auch|[[amarillo]]}}\n== Amarillo ({{Sp...
11927            Altamira  == Altamira ({{Sprache|Deutsch}}) ==\n=== {{Wo...
25267          Protestant  {{Siehe auch|[[protestant]]}}\n== Protestant (...
227948                Rus  {{Siehe auch|[[rus]]}}\n== Rus ({{Sprache|Deut...
20134                   Z  {{Siehe auch|[[z]], [[ź]], [[Ź]], [[ż]], [[Ż]]...
233911              Arras  {{Siehe auch|[[arras]]}}\n== Arras ({{Sprache|...
233604           Arequipa  == Arequipa ({{Sprache|Deutsch}}) ==\n=== {{Wo...
42219                   ä  {{Siehe auch|[[a]], [[A]], [[a-]], [[-a]], [[á...
234364             Austin  {{Siehe auch|[[āustin]]}}\n== Austin ({{Sprach...

In [50]:
trial_text=noun_df.loc[noun_df.title=='Spielball'].text.values[0]
trial_text

"== Spielball ({{Sprache|Deutsch}}) ==\n=== {{Wortart|Substantiv|Deutsch}}, {{m}} ===\n\n{{Deutsch Substantiv Übersicht\n|Genus=m\n|Nominativ Singular=Spielball\n|Nominativ Plural=Spielbälle\n|Genitiv Singular=Spielballes\n|Genitiv Singular*=Spielballs\n|Genitiv Plural=Spielbälle\n|Dativ Singular=Spielball\n|Dativ Singular*=Spielballe\n|Dativ Plural=Spielbällen\n|Akkusativ Singular=Spielball\n|Akkusativ Plural=Spielbälle\n}}\n\n{{Worttrennung}}\n:Spiel·ball, {{Pl.}} Spiel·bäl·le\n\n{{Aussprache}}\n:{{IPA}} {{Lautschrift|ˈʃpiːlˌbal}}\n:{{Hörbeispiele}} {{Audio|De-Spielball.ogg}}\n\n{{Bedeutungen}}\n:[1] ein [[Ball]], der zum [[spielen|Spielen]] [[bestimmt]] oder [[geeignet]] ist\n:[2] {{K|Sport}} Ballwechsel, der einen Spielabschnitt innerhalb eines [[Match]]es beenden kann\n:[3] ''übertragen:'' etwas oder jemand, der [[Objekt]] des [[Interesse]]s, des Spiels der Kräfte verschiedener [[Person]]en oder [[Personengruppe]]n ist, dabei aber [[passiv]], [[inaktiv]] bleibt oder bleiben muss\n\n{{Herkunft}}\n:[[Determinativkompositum]] aus dem Stamm des Verbs ''[[spielen]]'' und dem Substantiv ''[[Ball]]''\n\n{{Oberbegriffe}}\n:[1, 2] [[Ball]]\n\n{{Beispiele}}\n:[1] Viele bunte ''Spielbälle'' standen zur Auswahl.\n:[3] „Sie hoffen auf Arbeit, auf ein Leben ohne permanente Existenzangst - und werden in Europa zum ''Spielball'' der Politik: Etwa 23.000 Tunesier sind nach Italien geflohen.“<ref>{{Internetquelle|url=http://www.spiegel.de/politik/ausland/0,1518,757526,00.html|titel=Italien stellt Tunesiern Papiere für Weiterreise aus|autor=|werk=Der Spiegel (Online-Ausgabe)|zugriff=2011-05-29}}</ref>\n\n==== {{Übersetzungen}} ====\n{{Ü-Tabelle|1|G=ein Ball, der zum Spielen bestimmt oder geeignet ist|Ü-Liste=\n*{{en}}: {{Ü|en|game ball}}\n*{{fr}}: {{Ü|fr|ballon}}, {{Ü|fr|balle}} {{f}}, {{Ü|fr|jouet}}\n*{{it}}: {{Ü|it|giocattolo}}\n*{{pl}}: {{Ü|pl|piłka do gry}}\n*{{es}}: {{Ü|es|pelota}} {{f}}\n}}\n\n{{Ü-Tabelle|2|G=Sport: Ballwechsel, der einen Spielabschnitt innerhalb eines Matches beenden kann|Ü-Liste=\n*{{en}}: {{Ü|en|set point}}, ''Tennis:'' {{Ü|en|set ball}}\n*{{fr}}: {{Ü|fr|balle de set}} {{f}}\n*{{ca}}: {{Ü|ca|pilota de set}} {{f}}\n*{{es}}: {{Ü|es|punto de set}} {{m}}\n}}\n\n{{Ü-Tabelle|3|G=|Ü-Liste=\n*{{en}}: {{Ü|en|plaything}}\n*{{fr}}: {{Ü|fr|jouet}}\n*{{it}}: {{Ü|it|giocattolo}}\n*{{es}}: {{Ü|es|juguete}} {{m}}\n}}\n\n{{Referenzen}}\n:[*] {{Wikipedia-Suche|Spielball}}\n:[2] {{Ref-DWDS|Spielball}}\n:[1, 2] {{Ref-UniLeipzig|Spielball}}\n:[1–3] {{Ref-Duden|Spielball}}\n\n{{Quellen}}\n\n{{Ähnlichkeiten 1|Anagramme=[[Ballspiel]]}}"

In [51]:
to_match=re.findall('== .* \(\{\{Sprache\|.*\}\}\) ==',trial_text)
to_match

['== Spielball ({{Sprache|Deutsch}}) ==']

In [52]:
lst_1=trial_text.split('\n\n')
len(lst_1)

14

In [53]:
indices_lst=[]
for cur_match in to_match:
    for i,cur_lst in enumerate(lst_1):
        if cur_match in cur_lst and i!=0:
            indices_lst.append(i)
indices_lst

[]

In [73]:
import numpy as np

In [74]:
lang_lst=list(np.split(lst_1, indices_lst, axis=0))
lang_lst[0]

array(['{{Siehe auch|[[stein]], [[-stein]]}}\n{{Wort der Woche|17|2006}}\n== Stein ({{Sprache|Deutsch}}) ==\n=== {{Wortart|Substantiv|Deutsch}}, {{m}} ===',
       "{{Deutsch Substantiv Übersicht\n|Genus=m\n|Nominativ Singular=Stein\n|Nominativ Plural=Steine\n|Genitiv Singular=Steins\n|Genitiv Singular*=Steines\n|Genitiv Plural=Steine\n|Dativ Singular=Stein\n|Dativ Singular*=Steine\n|Dativ Plural=Steinen\n|Akkusativ Singular=Stein\n|Akkusativ Plural=Steine\n|Bild 1=Roscheider Hof BW 2015-08-01 15-05-43.jpg|mini|1|ein Haus aus ''Stein''\n|Bild 2=Beach Stones 2.jpg|mini|2|''Steine'' von einem [[Strand]]\n|Bild 3=Stapel bakstenen - Pile of bricks 2005 Fruggo.jpg|mini|3|Stapel von ''Steinen''\n|Bild 4=Diamonds 1.jpg|mini|4|Rohkristalle, die zu einem ''Stein'' geschliffen werden\n|Bild 5=Entrance_Stone_to_Rokkosan_Pasture.jpg|mini|7|''Stein'' am Rokkosan Pasture\n|Bild 6=Spielstein1.JPG|mini|9|verschiedene ''Steine'' zum Spielen\n|Bild 7=Nectarine stone.jpg|mini|10|''Stein'' der [[Nektarine]]\n}}",
       '{{Worttrennung}}\n:Stein, {{Pl.}} Stei·ne',
       '{{Aussprache}}\n:{{IPA}} {{Lautschrift|ʃtaɪ̯n}}\n:{{Hörbeispiele}} {{Audio|De-Stein.ogg}}, {{Audio|De-Stein2.ogg}}, {{Audio|LL-Q188 (deu)-Sebastian Wallroth-Stein.wav}}\n:{{Reime}} {{Reim|aɪ̯n|Deutsch}}',
       "{{Bedeutungen}}\n:[1] ''unzählbar:'' [[mineralisch]]es Material\n:[2] [[Körper]] aus mineralischem Material\n:[3] Bauelement für [[Gebäude]] und Ähnliches, [[Baustein]]\n:[4] kurz für [[Edelstein]] oder [[Schmuckstein]]\n:[5] in der [[Drogenszene]] [[Bezeichnung]] für [[Crack]]\n:[6] [[Lager]] aus [[Korund]] oder [[Granat]] in einem [[Uhrwerk]]\n:[7] Denkmal, Grabstein, Leichenstein\n:[8] ''Medizin:'' Klumpen harten Materials in [[Gallenblase]], [[Nase]] oder [[Niere]]\n:[9] einfach geformte [[Spielfigur]] für [[Brettspiel]]e\n:[10] der große, harte [[Kern]] der [[Steinfrucht]]",
       "{{Herkunft}}\n:das Substantiv ''[[Stein]], ({{m}}),'' das zum [[Standardwortschatz]] in der Bedeutung ''[[natürlich]]er, aus [[Mineralien]] bestehender, [[fest]]er, [[hart]]er [[Körper]], [[Fels]]'' gehört, ist seit dem 8. Jahrhundert nachgewiesen und wird abgeleitet von: {{goh.}} ''{{Ü|goh|stein}},'' {{gmh.}} ''{{Ü|gmh|stein}},'' {{osx.}} ''{{Ü|osx|stēn}},'' {{gml.}} ''{{Ü|gml|stēn}},'' {{dum.}} ''{{Ü|dum|steen}},'' {{nl.}} ''{{Ü|nl|steen}},'' {{ang.}} ''{{Ü|ang|stān}},'' {{en.}} ''{{Ü|en|stone}},'' {{non.}} ''{{Ü|non|steinn}},'' {{ofs.}} ''{{Ü|ofs|stēn}},'' {{sv.}} ''{{Ü|sv|sten}},'' [[neuisländisch]] ''{{Ü|is|steinn}},'' {{got.}} ''{{Üt|got|𐍃𐍄𐌰𐌹𐌽𐍃|stains}}'' ([[germanisch]] ''[[*staina-]] - [[Stein]]'') und kann wie {{el.}} ''{{Üt|el|στῖον|stī́on}} [[Kiesel]],'' [[altslawisch]] ''{{Üt|cu|stěna|}} - [[Wand]], [[Felswand]],'' [[serbokroatisch]] ''{{Ü|sh|stijèna}} - [[Felswand]], [[Stein]],'' {{ru.}} ''{{Üt|ru|стена}} - [[Wand]], [[Mauer]]'' als Bildung mit dem Suffix {{ie.}} ''[[-no-]]'' im Sinne von ''[[das Harte]], [[das Verdichtete]]'' zu einer Wurzel {{ie.}} ''[[*stāi-]], [[*stī̌-]] - (sich) [[verdichten]], [[zusammendrängen]], [[stopfen]], [[gerinnen]], [[stocken]]'' gestellt werden, zu der vielleicht auch [[altindisch]] ''[[styā́yatē]] - [[gerinnt]], [[wird fest]],'' {{el.}} ''{{Üt|el|στία|stī́ā}} - [[Steinchen]], [[Kiesel]], {{Üt|el|στέαρ|stéār}} ([[stehend]]es) [[Fett]], [[Talg]]'' (siehe auch [[Stearin]]), {{la.}} ''{{Ü|la|stiria|stīria}} [[Tropfen]], [[Eiszapfen]]'' {{lt.}} ''{{Ü|lt|stìngti}} - [[fest werden]], [[starr]], [[steif werden]], [[gerinnen]]'' gehören. […].<ref>{{Ref-Pfeifer|Stein}}</ref><ref>{{Lit-Kluge: Etymologisches Wörterbuch|A=25}}, Seite 880, unter: ''„[[Stein]]“''</ref><ref>{{Lit-Duden: Herkunftswörterbuch|A=1}}, Seite 675, unter: ''„[[Stein]]“''</ref>",
       '{{Synonyme}}\n:[1] [[Gestein]], [[Fels]]\n:[2] [[Brocken]], [[Bruch]], [[Felsen]], [[Felstrümmer]], [[Gesteinsstück]], [[Wacker]]\n:[3] [[Baustein]]\n:[4] [[Schmuckstein]]\n:[8] [[Konkrement]]\n:[9] [[Spielstein]]\n:[10] [[Steinkern]]',
       '{{Gegenwörter}}\n:[3] [[Holz]]\n:[9] ([[Schachfigur|Schach-]])[[Figur]]',
       '{{Oberbegriffe}}\n:[1] [[Material]], [[Substanz]], [[Stoff]]\n:[3] [[Bauelement]]\n:[4] [[Schmuck]]\n:[6] [[Zubehör]]\n:[7] [[Denkmal]]\n:[8] [[Konkrement]]\n:[9] [[Spielfigur]]\n:[10] [[Kern]], [[Same]]',
       '{{Unterbegriffe}}\n:[1] [[Alaunstein]], [[Basalt]], [[Bimsstein]], [[Blasensandstein]], [[Gneis]], [[Granit]], [[Feuerstein]] ([[Flint]]), [[Kalkstein]] ([[Kalk]]), [[Kupferstein]], [[Naturstein]], [[Marmor]], [[Ortstein]], [[Porphyr]], [[Sandstein]], [[Salzstein]], [[Speckstein]], [[Schamotte]], [[Tiefengestein]], [[Tuff]], [[Wacke]]\n:[2] [[Bautastein]], [[Betonstein]], [[Bimsstein]], [[Blaustein]], [[Bruchstein]], [[Granitstein]], [[Feldstein]], [[Feuerstein]], [[Flintstein]], [[Geröllstein]], [[Kieselstein]], [[Marmorstein]], [[Meteorstein]] ([[Meteorit]]), [[Naturstein]], [[Salzstein]], [[Schotterstein]], [[Tropfstein]], [[Veilstein]], [[Wackerstein]]\n:[2] [[Felsblock]], [[Findling]], [[Kiesel]]\n:[2] [[Altarstein]], [[Denkmalstein]], [[Gedenkstein]], [[Grabstein]], [[Grenzstein]], [[Handstein]], [[Kreuzstein]], [[Leichenstein]], [[Lügenstein]], [[Kilometerstein]], [[Markstein]], [[Mauerstein]], [[Meilenstein]], [[Prüfstein]], [[Rinnstein]], [[Spülstein]], [[Wappenstein]]\n:[3] [[Backstein]], [[Baustein]], [[Blendstein]]e, [[Dachstein]], [[Eckstein]], [[Grundstein]], [[Hohlblockstein]], [[Katzenkopf]], [[Klinker]], [[Kopfstein]], [[Kunststein]], [[Lüftungsstein]], [[Mauerstein]], [[Mosaikstein]], [[Pflasterstein]], [[Schamottestein]], [[Schlussstein]], [[Werkstein]], [[Ziegel]], [[Ziegelstein]]\n:[4] [[Edelstein]], [[Halbedelstein]]; [[Augenstein]], [[Bernstein]], [[Mondstein]], [[Similistein]], [[Sonnenstein]]\n:[7] [[Freiungsstein]], [[Gedenkstein]], [[Grabstein]], [[Grenzstein]], [[Herrschaftsgrenzstein]], [[Lästerstein]], [[Lichterstein]], [[Matronenstein]], [[Mordstein]], [[Pechölstein]], [[Peststein]], [[Prellstein]], [[Ruhestein]], [[Stolperstein]], [[Stundenstein]], [[Sühnestein]], [[Totenstein]], [[Votivstein]], [[Weihestein]]\n:[8] [[Bezoarstein]], [[Blasenstein]], [[Harnstein]], [[Nierenstein]], [[Gallenstein]], [[Xanthinstein]]\n:[9] [[Damestein]], [[Dominostein]], [[Legostein]], [[Mühlestein]], [[Spielstein]]\n:[10] [[Pfirsichstein]]\n:[3, 8] [[Nasenstein]]',
       "{{Beispiele}}\n:[1] Die Geräte sind aus Holz, Knochen oder ''Stein.''\n:[1] ''übertragen:'' Sie hat ein Herz aus ''Stein.''\n:[2] Als sie [die Schriftgelehrten und Pharisäer] nun fortfuhren, ihn zu fragen, richtete er [Jesus] sich auf und sprach zu ihnen: Wer unter Euch ohne Sünde ist, der werfe den ersten ''Stein'' auf sie [die Ehebrecherin].<ref>{{Bibel|Joh|8|7|LUT}}</ref>\n:[2] Wer wälzt den ''Stein'' von des Grabes Tür?\n:[3] ''Stein'' auf ''Stein'' / Das Häuschen wird bald fertig sein! - ''(Kinderlied)''\n:[4] Der ''Stein'' ist wunderschön geschliffen.\n:[4] „Sie trägt einen grünen Sweater, einen kurzen Rock und große Ohrringe mit falschen ''Steinen''.“<ref>{{Literatur|Autor=Erich Maria Remarque|Titel=Der schwarze Obelisk|TitelErg=Geschichte einer verspäteten Jugend. Roman|Auflage=5.|Verlag=Kiepenheuer & Witsch|Ort=Köln|Jahr=2003|ISBN=3-462-02725-5|Seiten=106.}} Erstmals 1956 erschienen.</ref>\n:[6] Das ist eine Uhr mit fünfzehn ''Steinen.''\n:[7] Am Pranger hängt ein ''Stein'', der Lästerstein, als Zeichen der Gerichtsbarkeit auf dem Markt.\n:[7] „Als er den ''Stein'' zurechtrückte, zerschrammte er sich die Schulter und riß sie auf.“<ref>{{Literatur | Autor=Marc Steadman | Titel=Schwarze Chronik | Übersetzer=[[w:Elisabeth Schnack|Elisabeth Schnack]] | TitelErg=Ein Südstaaten-Dekameron | Verlag=Fischer Taschenbuch Verlag | Ort=Frankfurt am Main | Jahr=1980 | ISBN=3-596-22489-6 | Seiten=289 | Originaltitel=MacAfee county | Kommentar=englische Originalausgabe 1970 }}.</ref>\n:[8] Die ''Steine'' schmerzen heftig.\n:[9] Zwei ''Steine'' aufeinander ergeben eine Dame.\n:[10] Den ''Stein'' musst du ausspucken.",
       "{{Redewendungen}}\n:[1] [[Stein und Bein schwören|''Stein'' und Bein schwören]]\n:[2] [[ein Tropfen auf den heißen Stein|ein Tropfen auf den heißen ''Stein'']]\n:[2] [[einen Stein ins Rollen bringen|einen ''Stein'' ins Rollen bringen]], [[der Stein kommt ins Rollen|der ''Stein'' kommt ins Rollen]]\n:[2] [[jemandem Steine in den Weg legen|jemandem ''Steine'' in den Weg legen]]\n:[2] [[Stein des Anstoßes|''Stein'' des Anstoßes]]\n:[3] [[kein Stein bleibt auf dem anderen|kein ''Stein'' bleibt auf dem anderen]]\n:[4] [[dir wird schon kein Stein aus der Krone fallen|dir wird schon kein ''Stein'' aus der Krone fallen]]\n:[9] [[bei jemandem einen Stein im Brett haben|bei jemandem einen ''Stein'' im Brett haben]]\n:[[über Stock und Stein|über Stock und ''Stein'']]\n:[[wer frei von Schuld, der werfe den ersten Stein|wer frei von Schuld, der werfe den ersten ''Stein'']]",
       "{{Sprichwörter}}\n:[[wer im Glashaus sitzt, soll nicht mit Steinen werfen|wer im Glashaus sitzt, soll nicht mit ''Steinen'' werfen]]\n:[[wer ohne Sünde ist, der werfe den ersten Stein|wer ohne Sünde ist, der werfe den ersten ''Stein'']]",
       '{{Wortbildungen}}\n:[[Abziehstein]], [[Flintenstein]], [[Handstein]], [[Mahlstein]], [[Mühlstein]], [[Rollstein]], [[Schleifstein]], [[Sensenstein]], [[Spülstein]], [[Strassstein]], [[Taufstein]], [[Trittstein]], [[Wetzstein]]\n:[1] [[Braunstein]], [[Harnstein]], [[Höllenstein]], [[Kesselstein]], [[Mondstein]], [[Steinabfall]], [[Steinanker]], [[Steinaxt]], [[Steinblock]], [[Steinbohrer]], [[Steinbrecher]], [[Steinbrocken]], [[Steinbruch]], [[Steinbrücke]], [[Steindruck]], [[Steineiche]], [[steinern]], [[Steinewerfer]], [[Steinfischerei]], [[Steingebäude]], [[Steingravur]], [[Steingut]], [[steinhart]], [[Steinhauer]], [[Steinhaus]], [[Steinhäuschen]], [[Steinkirche]], [[Steinkohle]], [[Steinlaus]], [[Steinmehl]], [[Steinrelief]], [[Steinsäge]], [[Steinsalz]], [[Steinsarg]], [[Steinsarkophag]], [[Steinsäule]], [[Steinschicht]], [[Steinstaub]], [[Steintreppe]], [[Steinwall]], [[Steinwolle]], [[Steinwüste]], [[Steinzangerei]], [[Steinzeit]], [[Steinzeug]], [[Urinstein]], [[versteinern]], [[Weinstein]], [[Zahnstein]]\n:[2] [[Steinadler]], [[steinalt]], [[Steinartefakt]], [[Steinaxt]], [[Steinbank]], [[Steinbeil]], [[Steinbock]], [[Steinbutt]], [[Steingarten]], [[Steingeiß]], [[Steingeld]], [[Steingerät]], [[Steinhaufen]], [[steinig]], [[steinigen]], [[Steinmesser]], [[Steinpilz]], [[Steinschlag]], [[Steinschleuder]], [[Steinschloss]], [[Steintisch]], [[Steinwerkzeug]], [[Steinwurf]], [[Stolperstein]]\n:[3] [[Bogenstein]], [[Bordstein]], [[Rinnstein]], [[Schornstein]], [[Steinbalustrade]], [[Steinboden]], [[Steinfliese]], [[Steinfußboden]], [[Steingrab]], [[Steinmauer]], [[Steinmetz]], [[Steinpflaster]], [[Steinpiste]], [[steinreich]], [[Steinstufe]], [[Steinweg]]\n:[4] [[Steinschneider]]\n:[8] [[Steinleiden]]\n:[10] [[Steinfrucht]], [[Steinobst]]',
       "==== {{Übersetzungen}} ====\n{{Ü-Tabelle|1|G=unzählbar: mineralisches Material|Ü-Liste=\n*{{hy}}: {{Üt|hy|վէմ|wemm}}, {{Üt|hy|քար|kar}}\n*{{az}}: {{Ü|az|daş}}\n*{{eu}}: {{Ü|eu|harri}}\n*{{bs}}: {{Üt|bs|камен|kamen}} {{m}}\n*{{bg}}: {{Üt|bg|камък|kamăk}}\n*{{zh}}: {{Üt|zh|石|shí}}\n*{{da}}: {{Ü|da|sten}} {{u}}\n*{{en}}: {{Ü|en|stone}}, {{Ü|en|rock}}\n*{{myv}}: {{Üt|myv|кев|kev}}\n*{{eo}}: {{Ü|eo|ŝtono}}\n*{{et}}: {{Ü|et|kivi}}\n*{{fo}}: {{Ü|fo|steinur}} {{m}}\n*{{fi}}: {{Ü|fi|kivi}}\n*{{fr}}: {{Ü|fr|pierre}} {{f}}\n*{{gl}}: {{Ü|gl|pedra}} {{f}}\n*{{ka}}: {{Üt|ka|ქვა|kva}}\n*{{el}}: {{Üt|el|πέτρα|pétra}} {{f}}, {{Üt|el|λίθος|líthos}} {{mf}}\n*{{kl}}: {{Ü|kl|ujarak}}\n*{{he}}: {{Üt|he|אבן\u200e| ʾéven|אֶבֶן\u200e}} {{f}}\n*{{io}}: {{Ü|io|petro}}\n*{{ia}}: {{Ü|ia|petra}}\n*{{is}}: {{Ü|is|steinn}}\n*{{it}}: {{Ü|it|pietra}}, {{Ü|it|sasso}}\n*{{ca}}: {{Ü|ca|roca}} {{f}}, {{Ü|ca|pedra}} {{f}}\n*{{la}}: {{Ü|la|petra}}\n*{{ltg}}: {{Ü|ltg|akmiņs}}\n*{{lv}}: {{Ü|lv|akmens}}\n*{{lt}}: {{Ü|lt|akmuo}}\n*{{mk}}: {{Üt|mk|камен|kamen}} {{m}}\n*{{lus}}: {{Ü|lus|lung}}\n*{{nds}}: {{Ü|nds|Steen}}, {{Ü|nds|Stejn}}\n*{{nl}}: {{Ü|nl|steen}}\n*{{se}}: {{Ü|se|geađgi}}\n*{{no}}:\n**{{nb}}: {{Ü|nb|stein}} {{m}}, {{Ü|nb|sten}} {{m}}\n**{{nn}}: {{Ü|nn|stein}} {{m}}\n*{{oc}}: {{Ü|oc|pèira}} {{f}}\n*{{pl}}: {{Ü|pl|kamień}} {{m}}\n*{{pt}}: {{Ü|pt|pedra}} {{f}}\n*{{ro}}: {{Ü|ro|piatră}} {{f}}, {{Ü|ro|kamena}}\n*{{ru}}: {{Üt|ru|камень}} {{m}}\n*{{sc}}: {{Ü|sc|preda}}\n*{{sv}}: {{Ü|sv|sten}}\n*{{sr}}: {{Üt|sr|камен|kamen}} {{m}}\n*{{sh}}: {{Üt|sh|камен|kamen}} {{m}}\n*{{sk}}: {{Ü|sk|kameň}} {{m}}\n*{{sl}}: {{Ü|sl|kamen}}\n*{{wen}}:\n**{{dsb}}: {{Ü|dsb|kamjeń}} {{m}}, {{Ü|dsb|kamušk}} {{m}}\n**{{hsb}}: {{Ü|hsb|kamjeń}} {{m}}\n*{{es}}: {{Ü|es|piedra}} {{f}}\n*{{tg}}: {{Üt|tg|санг|sang}}\n*{{ty}}: {{Ü|ty|ʻōfaʻi}}\n*{{cs}}: {{Ü|cs|kámen}} {{m}}\n*{{tr}}: {{Ü|tr|taş}}\n*{{uk}}: {{Üt|uk|камінь}} {{m}}\n*{{hu}}: {{Ü|hu|kő}}\n*{{be}}: {{Üt|be|камень}} {{m}}\n|Dialekttabelle=\n*Mitteldeutsch:\n**{{pfl}}: [?] {{Lautschrift|ʃdɛː}}, {{Lautschrift|ʃdɛ̃ː}}\n**Berlinerisch:\n*Oberdeutsch:\n**Schwäbisch: [?] Schdoi, Schdoa\n**{{bar}}: [?] Schdoa ''pl.'' Schdoana, alternativ: Schdaa ''pl.'' Schdooi\n}}",
       "{{Ü-Tabelle|2|G=Körper aus mineralischem Material|Ü-Liste=\n*{{hy}}: {{Üt|hy|վէմ|wemm}}, {{Üt|hy|քար|kar}}\n*{{az}}: {{Ü|az|daş}}\n*{{eu}}: {{Ü|eu|harri}}\n*{{bs}}: {{Üt|bs|камен|kamen}} {{m}}\n*{{bg}}: {{Üt|bg|камък|kamăk}}\n*{{zh}}:\n**{{zh-tw}}: {{Üt|zh|石頭|shítou}}\n**{{zh-cn}}: {{Üt|zh|石头|shítou}}\n*{{en}}: {{Ü|en|stone}}, {{Ü|en|rock}}, {{Ü|en|boulder}}\n*{{eo}}: {{Ü|eo|ŝtono}}\n*{{fr}}: {{Ü|fr|pierre}} {{f}}, {{Ü|fr|caillou}} {{m}}\n*{{el}}: {{Üt|el|πέτρα|pétra}} {{f}}, {{Üt|el|λίθος|líthos}} {{mf}}\n*{{ia}}: {{Ü|ia|petra}}\n*{{is}}: {{Ü|is|steinn}}\n*{{it}}: {{Ü|it|pietra}}, {{Ü|it|sasso}}\n*{{ja}}: {{Üt|ja|石|いし, ishi}}\n*{{ca}}: {{Ü|ca|pedra}} {{f}}\n*{{tlh}}: {{Ü|tlh|nagh}}\n*{{ku}}:\n**{{kmr}}: {{Ü|kmr|kevir}}\n*{{la}}: {{Ü|la|lapis}}\n*{{lv}}: {{Ü|lv|akmens}}\n*{{mk}}: {{Üt|mk|камен|kamen}} {{m}}\n*{{lus}}: {{Ü|lus|lung}}\n*{{nds}}: {{Ü|nds|Steen}}, {{Ü|nds|Stejn}}\n*{{nl}}: {{Ü|nl|steen}}\n*{{no}}:\n**{{nb}}: {{Ü|nb|stein}} {{m}}, {{Ü|nb|sten}} {{m}}\n**{{nn}}: {{Ü|nn|stein}} {{m}}\n*{{oc}}: {{Ü|oc|pèira}} {{f}}\n*{{pl}}: {{Ü|pl|kamień}} {{m}}\n*{{pt}}: {{Ü|pt|pedra}} {{f}}\n*{{ro}}: {{Ü|ro|piatră}} {{f}}, {{Ü|ro|kamena}}\n*{{ru}}: {{Üt|ru|камень}} {{m}}\n*{{sc}}: {{Ü|sc|preda}}\n*{{sv}}: {{Ü|sv|sten}}\n*{{sr}}: {{Üt|sr|камен|kamen}} {{m}}\n*{{sh}}: {{Üt|sh|камен|kamen}} {{m}}\n*{{sk}}: {{Ü|sk|kameň}} {{m}}\n*{{sl}}: {{Ü|sl|kamen}}\n*{{wen}}:\n**{{dsb}}: {{Ü|dsb|kamjeń}} {{m}}, {{Ü|dsb|kamušk}} {{m}}\n**{{hsb}}: {{Ü|hsb|kamjeń}} {{m}}\n*{{es}}: {{Ü|es|piedra}} {{f}}\n*{{tg}}: {{Üt|tg|санг|sang}}\n*{{cs}}: {{Ü|cs|kámen}} {{m}}\n*{{tr}}: {{Ü|tr|taş}}\n*{{uk}}: {{Üt|uk|камінь}} {{m}}\n*{{be}}: {{Üt|be|камень}} {{m}}\n|Dialekttabelle=\n*Mitteldeutsch:\n**{{pfl}}: [?] {{Lautschrift|ʃdɛː}}, {{Lautschrift|ʃdɛ̃ː}}\n**Berlinerisch:\n*Oberdeutsch:\n**Schwäbisch: [?] Schdoi, Schdoa\n**{{bar}}: [?] Schdoa ''pl.'' Schdoana, alternativ: Schdaa ''pl.'' Schdooi\n}}",
       "{{Ü-Tabelle|3|G=Bauelement für Gebäude und Ähnliches, Baustein|Ü-Liste=\n*{{hy}}: {{Üt|hy|վէմ|wemm}}, {{Üt|hy|քար|kar}}\n*{{bs}}: {{Üt|bs|камен|kamen}} {{m}}, {{Üt|bs|цигла|cigla}} {{f}}\n*{{en}}: {{Ü|en|brick}}, {{Ü|en|stone}}, {{Ü|en|building block}}\n*{{fr}}: {{Ü|fr|pierre}} {{f}}, {{Ü|fr|brique}} {{f}}\n*{{ka}}: {{Üt|ka|აგური|aguri}}\n*{{el}}: {{Üt|el|οικοδομικός|ikodomikós líthos|οικοδομικός λίθος}} {{m}}\n*{{he}}: {{Üt|he|אבן\u200e|ʾéven|אֶבֶן\u200e}} {{f}}\n*{{ia}}: {{Ü|ia|petra}}\n*{{it}}: {{Ü|it|mattone}} {{m}}\n*{{ca}}: {{Ü|ca|pedra}} {{f}}\n*{{la}}: {{Ü|la|lapis}}\n*{{mk}}: {{Üt|mk|камен|kamen}} {{m}}, {{Üt|mk|цигла|cigla}} {{f}}\n*{{nds}}: {{Ü|nds|Steen}}, {{Ü|nds|Stejn}}\n*{{nl}}: {{Ü|nl|steen}}\n*{{no}}:\n**{{nb}}: {{Ü|nb|stein}} {{m}}, {{Ü|nb|sten}} {{m}}\n**{{nn}}: {{Ü|nn|stein}} {{m}}\n*{{oc}}: {{Ü|oc|pèira}} {{f}}\n*{{pt}}: {{Ü|pt|pedra}} {{f}}\n*{{ro}}: {{Ü|ro|piatră}} {{f}}, {{Ü|ro|kamena}}\n*{{ru}}: {{Üt|ru|камень}} {{m}}\n*{{sr}}: {{Üt|sr|камен|kamen}} {{m}}, {{Üt|sr|цигла|cigla}} {{f}}\n*{{sh}}: {{Üt|sh|камен|kamen}} {{m}}, {{Üt|sh|цигла|cigla}} {{f}}\n*{{sl}}: {{Ü|sl|zidak}}\n*{{cs}}: {{Ü|cs|kámen}} {{m}}\n*{{uk}}: {{Üt|uk|камінь}} {{m}}\n*{{be}}: {{Üt|be|камень}} {{m}}\n|Dialekttabelle=\n*Mitteldeutsch:\n**{{pfl}}: [?] {{Lautschrift|ʃdɛː}}, {{Lautschrift|ʃdɛ̃ː}}\n**Berlinerisch:\n*Oberdeutsch:\n**Schwäbisch: [?] Schdoi, Schdoa\n**{{bar}}: [?] Schdoa ''pl.'' Schdoana, alternativ: Schdaa ''pl.'' Schdooi\n}}",
       "{{Ü-Tabelle|4|G=kurz für Edelstein oder Schmuckstein|Ü-Liste=\n*{{bs}}: {{Üt|bs|драги камен|dragi kamen}} {{m}}\n*{{en}}: {{Ü|en|stone}}\n*{{eo}}: {{Ü|eo|ŝtono}}\n*{{fr}}: {{Ü|fr|pierre}} {{f}}\n*{{el}}: {{Üt|el|πολύτιμος λίθος|polýtimos líthos}} {{m}}\n*{{ia}}: {{Ü|ia|joiel}}\n*{{ca}}: {{Ü|ca|pedra preciosa}} {{f}}\n*{{mk}}: {{Üt|mk|драги камен|dragi kamen}} {{m}}\n*{{nds}}: {{Ü|nds|Steen}}, {{Ü|nds|Stejn}}\n*{{nl}}: {{Ü|nl|steen}}\n*{{no}}:\n**{{nb}}: {{Ü|nb|stein}} {{m}}, {{Ü|nb|sten}} {{m}}\n**{{nn}}: {{Ü|nn|stein}} {{m}}\n*{{pl}}: {{Ü|pl|kamień}} {{m}}\n*{{ro}}: {{Ü|ro|piatră}} {{f}}, {{Ü|ro|kamena}}\n*{{sr}}: {{Üt|sr|драги камен|dragi kamen}} {{m}}\n*{{sh}}: {{Üt|sh|драги камен|dragi kamen}} {{m}}\n*{{cs}}: {{Ü|cs|kámen}} {{m}}\n|Dialekttabelle=\n*Mitteldeutsch:\n**{{pfl}}: [?] {{Lautschrift|ʃdɛː}}, {{Lautschrift|ʃdɛ̃ː}}\n**Berlinerisch:\n*Oberdeutsch:\n**Schwäbisch: [?] Schdoi, Schdoa\n**{{bar}}: [?] Schdoa ''pl.'' Schdoana, alternativ: Schdaa ''pl.'' Schdooi\n}}",
       "{{Ü-Tabelle|5|G=in der Drogenszene Bezeichnung für Crack|Ü-Liste=\n*{{en}}: {{Ü|en|stone}}, {{Ü|en|rock}}, {{Ü|en|crack rock}}\n*{{eo}}: {{Ü|eo|ŝtono}}\n*{{nds}}: {{Ü|nds|Steen}}, {{Ü|nds|Stejn}}\n|Dialekttabelle=\n*Mitteldeutsch:\n**{{pfl}}: [?] {{Lautschrift|ʃdɛː}}, {{Lautschrift|ʃdɛ̃ː}}\n**Berlinerisch:\n*Oberdeutsch:\n**Schwäbisch: [?] Schdoi, Schdoa\n**{{bar}}: [?] Schdoa ''pl.'' Schdoana, alternativ: Schdaa ''pl.'' Schdooi\n}}",
       "{{Ü-Tabelle|6|G=Lager aus Korund oder Granat in einem Uhrwerk|Ü-Liste=\n*{{bs}}: {{Üt|bs|камен|kamen}} {{m}}\n*{{en}}: {{Ü|en|jewel}}\n*{{eo}}: {{Ü|eo|ŝtono}}\n*{{mk}}: {{Üt|mk|камен|kamen}} {{m}}\n*{{nds}}: {{Ü|nds|Steen}}, {{Ü|nds|Stejn}}\n*{{no}}:\n**{{nb}}: {{Ü|nb|stein}} {{m}}, {{Ü|nb|sten}} {{m}}\n**{{nn}}: {{Ü|nn|stein}} {{m}}\n*{{pl}}: {{Ü|pl|kamień}} {{m}}\n*{{ro}}: {{Ü|ro|piatră}} {{f}}, {{Ü|ro|kamena}}\n*{{sr}}: {{Üt|sr|камен|kamen}} {{m}}\n*{{sh}}: {{Üt|sh|камен|kamen}} {{m}}\n*{{cs}}: {{Ü|cs|kámen}} {{m}}\n|Dialekttabelle=\n*Mitteldeutsch:\n**{{pfl}}: [?] {{Lautschrift|ʃdɛː}}, {{Lautschrift|ʃdɛ̃ː}}\n**Berlinerisch:\n*Oberdeutsch:\n**Schwäbisch: [?] Schdoi, Schdoa\n**{{bar}}: [?] Schdoa ''pl.'' Schdoana, alternativ: Schdaa ''pl.'' Schdooi\n}}",
       "{{Ü-Tabelle|7|G=Denkmal, Grabstein, Leichenstein|Ü-Liste=\n*{{bs}}: {{Üt|bs|споменик|spomenik}} {{m}}\n*{{en}}: {{Ü|en|stone}}\n*{{eo}}: {{Ü|eo|ŝtono}}\n*{{fr}}: {{Ü|fr|pierre}} {{f}}\n*{{mk}}: {{Üt|mk|споменик|spomenik}} {{m}}\n*{{nds}}: {{Ü|nds|Steen}}, {{Ü|nds|Stejn}}\n*{{no}}:\n**{{nb}}: {{Ü|nb|stein}} {{m}}, {{Ü|nb|sten}} {{m}}\n**{{nn}}: {{Ü|nn|stein}} {{m}}\n*{{ro}}: {{Ü|ro|piatră}} {{f}}, {{Ü|ro|kamena}}\n*{{sr}}: {{Üt|sr|споменик|spomenik}} {{m}}\n*{{sh}}: {{Üt|sh|споменик|spomenik}} {{m}}\n|Dialekttabelle=\n*Mitteldeutsch:\n**{{pfl}}: [?] {{Lautschrift|ʃdɛː}}, {{Lautschrift|ʃdɛ̃ː}}\n**Berlinerisch:\n*Oberdeutsch:\n**Schwäbisch: [?] Schdoi, Schdoa\n**{{bar}}: [?] Schdoa ''pl.'' Schdoana, alternativ: Schdaa ''pl.'' Schdooi\n}}",

In [75]:
lang_lst[1]

array(['== Stein ({{Sprache|Norwegisch}}) ==\n=== {{Wortart|Substantiv|Norwegisch}}, {{m}}, {{Wortart|Vorname|Norwegisch}} ===',
       '{{Worttrennung}}\n:Stein',
       '{{Aussprache}}\n:{{IPA}} {{Lautschrift||spr=no}}\n:{{Hörbeispiele}} {{Audio|}}',
       '{{Bedeutungen}}\n:[1] [[norwegisch]]er männlicher [[Vorname]]',
       "{{Herkunft}}\n:vom [[altnordisch]]en ''{{Ü|non|steinn}}'' „Stein“ oder vom [[altenglisch]]en ''{{Ü|ang|stán}}'' „Stein“",
       '{{Namensvarianten}}\n:[1] [[Steen]], [[Sten]]',
       '{{Weibliche Namensvarianten}}\n:[1] [[Stenetta]]',
       '{{Bekannte Namensträger}}\n:[1] [[w:no:Stein Eriksen|Stein Eriksen]], [[w:no:Stein Kollshaugen|Stein Kollshaugen]], [[w:no:Stein Rokkan|Stein Rokkan]], [[w:no:Stein Rosenlund|Stein Rosenlund]], [[w:no:Stein Tønnesson|Stein Tønnesson]]',
       '{{Beispiele}}\n:[1] {{Beispiele fehlen}}',
       '==== {{Übersetzungen}} ====\n{{Ü-Tabelle|1|G=norwegischer männlicher Vorname|Ü-Liste=\n*{{da}}: {{Ü|da|Steen}}, {{Ü|da|Sten}}\n*{{en}}: {{Ü|en|Stone}}\n*{{fo}}: {{Ü|fo|Steinur}}\n*{{is}}: {{Ü|is|Steini}}, {{Ü|is|Steinn}}\n}}',
       '{{Referenzen}}\n:[1] {{Wikipedia|spr=no|Stein}}'], dtype='<U2110')

In [123]:
re.findall('=== {{Wortart\|.* ===',trial_text)

['=== {{Wortart|Substantiv|Deutsch}}, {{n}}, {{Wortart|Buchstabe|Deutsch}}, {{Wortart|Abkürzung|Deutsch}} ===',
 '=== {{Wortart|Symbol|International}} ===',
 '=== {{Wortart|Abkürzung|International}} ===',
 '=== {{Wortart|Substantiv|Albanisch}}, {{f}}, {{Wortart|Buchstabe|Albanisch}} ===',
 '=== {{Wortart|Konjunktion|Albanisch}} ===',
 '=== {{Wortart|Partikel|Albanisch}} ===',
 '=== {{Wortart|Interjektion|Albanisch}} ===',
 '=== {{Wortart|Buchstabe|Dänisch}} ===',
 '=== {{Wortart|Artikel|Englisch}} ===',
 '=== {{Wortart|Buchstabe|Esperanto}} ===',
 '=== {{Wortart|Buchstabe|Estnisch}} ===',
 '=== {{Wortart|Substantiv|Französisch}}, {{m}}, {{Wortart|Buchstabe|Französisch}} ===',
 '=== {{Wortart|Konjugierte Form|Französisch}} ===',
 '=== {{Wortart|Substantiv|Irisch}}, {{n}}, {{Wortart|Buchstabe|Irisch}} ===',
 '=== {{Wortart|Buchstabe|Isländisch}} ===',
 '=== {{Wortart|Buchstabe|Italienisch}} ===',
 '=== {{Wortart|Präposition|Italienisch}} ===',
 '=== {{Wortart|Buchstabe|Kaschubisch}} ===',
 '=== {{Wortart|Präposition|Katalanisch}} ===',
 '=== {{Wortart|Buchstabe|Kikuyu}} ===',
 '=== {{Wortart|Buchstabe|Krimtatarisch}} ===',
 '=== {{Wortart|Interjektion|Latein}} ===',
 '=== {{Wortart|Präposition|Latein}} ===',
 '=== {{Wortart|Buchstabe|Lettgallisch}} ===',
 '=== {{Wortart|Buchstabe|Lettisch}} ===',
 '=== {{Wortart|Interjektion|Lettisch}} ===',
 '=== {{Wortart|Buchstabe|Litauisch}} ===',
 '=== {{Wortart|Buchstabe|Maltesisch}} ===',
 '=== {{Wortart|Substantiv|Niederländisch}}, {{mf}},  {{Wortart|Buchstabe|Niederländisch}} ===',
 '=== {{Wortart|Abkürzung|Niederländisch}} ===',
 '=== {{Wortart|Buchstabe|Niedersorbisch}} ===',
 '=== {{Wortart|Konjunktion|Niedersorbisch}} ===',
 '=== {{Wortart|Partikel|Niedersorbisch}} ===',
 '=== {{Wortart|Konjunktion|Obersorbisch}} ===',
 '=== {{Wortart|Substantiv|Polnisch}}, {{n}}, {{Wortart|Buchstabe|Polnisch}} ===',
 '=== {{Wortart|Konjunktion|Polnisch}} ===',
 '=== {{Wortart|Partikel|Polnisch}} ===',
 '=== {{Wortart|Interjektion|Polnisch}} ===',
 '=== {{Wortart|Buchstabe|Rumänisch}} ===',
 '=== {{Wortart|Konjugierte Form|Rumänisch}} ===',
 '=== {{Wortart|Buchstabe|Shona}} ===',
 '=== {{Wortart|Buchstabe|Slowakisch}} ===',
 '=== {{Wortart|Konjunktion|Slowakisch}} ===',
 '=== {{Wortart|Interjektion|Slowakisch}} ===',
 '=== {{Wortart|Buchstabe|Slowenisch}} ===',
 '=== {{Wortart|Buchstabe|Spanisch}} ===',
 '=== {{Wortart|Präposition|Spanisch}} ===',
 '=== {{Wortart|Buchstabe|Tschechisch}} ===',
 '=== {{Wortart|Konjunktion|Tschechisch}} ===',
 '=== {{Wortart|Artikel|Ungarisch}} ===',
 '=== {{Wortart|Buchstabe|Ungarisch}} ===',
 '=== {{Wortart|Buchstabe|Usbekisch}} ===']

In [91]:
re.search(r"={{Siehe auch|\[\[(.*?)\]\]}}", trial_text).group(1)

'hallo]], [[halló'

In [79]:
re.search(r"=== {{Wortart\|(.*?)\|(.*?)}} ===", trial_text).group(2)

'Deutsch}}, {{m'

In [75]:
import re

def extract_wiktionary_info(text):
    # Extracting word type and gender
    word_type_match = re.search(r"=== {{Wortart\|(.*?)\|(.*?)}} ===", text)
    if word_type_match:
        word_type = word_type_match.group(1)
        gender = word_type_match.group(2)
        print("Word Type:", word_type)
        print("Gender:", gender)

    # Extracting declensions
    declensions_match = re.search(r"{{Deutsch Substantiv Übersicht\n\|(.*?)\n}}", text, re.DOTALL)
    if declensions_match:
        declensions_data = declensions_match.group(1)
        print("Declensions:", declensions_data)

    # Extracting pronunciation
    pronunciation_match = re.search(r":{{IPA}} {{Lautschrift\|(.*?)}}", text)
    if pronunciation_match:
        pronunciation = pronunciation_match.group(1)
        print("Pronunciation:", pronunciation)

    # Extracting meanings
    meanings_match = re.search(r"{{Bedeutungen}}\n:(.*?)\n", text, re.DOTALL)
    if meanings_match:
        meanings = meanings_match.group(1)
        print("Meanings:", meanings)

    # Extracting synonyms
    synonyms_match = re.search(r"{{Synonyme}}\n:(.*?)\n", text, re.DOTALL)
    if synonyms_match:
        synonyms = synonyms_match.group(1)
        print("Synonyms:", synonyms)

    # Extracting examples
    examples_match = re.search(r"{{Beispiele}}\n:(.*?)\n", text, re.DOTALL)
    if examples_match:
        examples = examples_match.group(1)
        print("Examples:", examples)

    # Extracting translations
    translations_match = re.search(r"==== {{Übersetzungen}} ====\n(.*?)\n{{Referenzen}}", text, re.DOTALL)
    if translations_match:
        translations = translations_match.group(1)
        print("Translations:", translations)

if __name__ == "__main__":
    wiktionary_text = ''' ... (the provided content) ... '''
    extract_wiktionary_info(wiktionary_text)

In [100]:
trial_text.split('\n')

['== Altstadt ({{Sprache|Deutsch}}) ==',
 '=== {{Wortart|Substantiv|Deutsch}}, {{f}} ===',
 '',
 '{{Deutsch Substantiv Übersicht',
 '|Genus=f',
 '|Nominativ Singular=Altstadt',
 '|Nominativ Plural=Altstädte',
 '|Genitiv Singular=Altstadt',
 '|Genitiv Plural=Altstädte',
 '|Dativ Singular=Altstadt',
 '|Dativ Plural=Altstädten',
 '|Akkusativ Singular=Altstadt',
 '|Akkusativ Plural=Altstädte',
 "|Bild 1=SalzburgerAltstadt02b.jpg|mini|1|die ''Altstadt'' von [[Salzburg]]",
 "|Bild 2=|mini|1|''Altstadt'' von [[Königsberg]] (nunmehr [[Kaliningrad]])",
 '}}',
 '',
 '{{Worttrennung}}',
 ':Alt·stadt, {{Pl.}} Alt·städ·te',
 '',
 '{{Aussprache}}',
 ':{{IPA}} {{Lautschrift|ˈaltˌʃtat}}',
 ':{{Hörbeispiele}} {{Audio|De-Altstadt.ogg}}',
 ':{{Reime}} {{Reim|altʃtat|Deutsch}}',
 '',
 '{{Bedeutungen}}',
 ':[1] der älteste Teil einer Stadt, sofern dieser (typischerweise) vor 1900 gebaut wurde oder in einem entsprechendem Stil wiederaufgebaut worden ist',
 '',
 '{{Herkunft}}',
 ":[[Determinativkompositum]] aus ''[[alt]]'' und ''[[Stadt]]''",
 '',
 '{{Sinnverwandte Wörter}}',
 ':[1] [[Altort]], [[Innenstadt]]',
 '',
 '{{Gegenwörter}}',
 ':[1] [[Neustadt]]',
 '',
 '{{Oberbegriffe}}',
 ':[1] [[Stadtteil]]',
 '',
 '{{Beispiele}}',
 ":[1] In der ''Altstadt'' von Prag gibt es Gebäude aus dem 14. Jahrhundert.",
 ":[1] Seit Ende des Zweiten Weltkrieges hat Berlin keine ''Altstadt'' mehr.",
 ":[1] „Der Reiseführer setzte unbeirrt seine Tour fort, und bald darauf betraten wir die ''Altstadt'' von Kairo mit ihren vielen Kirchen.“<ref>{{Literatur|Autor=Hamed Abdel-Samad|Titel=Mein Abschied vom Himmel|TitelErg= Aus dem Leben eines Muslims Deutschland |Verlag=Knaur Taschenbuch Verlag |Ort=München|Jahr= 2010|Seiten= 176|ISBN= 978-3-426-78408-2}}.</ref>",
 ":[1] „Es hat mich immer gewundert, dass die Neustadt so hieß, obwohl dort viel mehr alte und verfallene Häuser standen als in der ''Altstadt,'' die nach der Zerstörung größtenteils abgerissen und neu gebaut wurde. Eine neue ''Altstadt,'' funktional und uncharmant.“<ref>{{Literatur|Autor=Jan Josef Liefers|Titel=Soundtrack meiner Kindheit|Verlag=Rowohlt|Ort= Reinbek|Jahr=2011|Seiten=199.|ISBN= 978-3-499-62592-3}}</ref>",
 ":[1] „Sie mündet in die Warschauer ''Altstadt,'' der man es ebenfalls nicht ansieht, daß sie nur vierzig Jahre alt ist.“<ref>{{Literatur|Autor=Radek Knapp|Titel=Gebrauchsanweisung für Polen|Auflage=5.|Verlag=Piper|Ort= München, Zürich |Jahr=2011}}, Seite 38. ISBN 978-3-423-492-27536-1.</ref>",
 ":[1] „Im Rahmen der BUGA entsteht hier ein attraktiver, großzügiger Landschaftspark, der einen Gegenpol zu dem regen Leben in der ''Altstadt'' bietet.“<ref>{{Literatur | Autor= Joana Müller |Herausgeber= Thomas Brühne, Stefan Harnischmacher |Titel= Koblenz blüht auf: Die BUGA 2011 als Chance einer nachhaltigen Stadtentwicklung |Sammelwerk= Koblenz und sein Umland. Eine Auswahl geographischer Exkursionen | Verlag= Bouvier | Ort= Bonn | Jahr=2011 | Seiten= 30-37, Zitat Seite 31.| ISBN=978-3-416-03338-1}}</ref>",
 '',
 '{{Wortbildungen}}',
 ':[[Altstadterhaltungsfonds]], [[Altstadtmauer]], [[Altstadtquartier]], [[Altstadtpflaster]], [[Altstadtsanierung]], [[Altstadttor]], [[Altstadtviertel]], [[Altstadtwochenmarkt]]',
 '',
 '==== {{Übersetzungen}} ====',
 '{{Ü-Tabelle|1|G=|Ü-Liste=',
 '*{{en}}: {{Ü|en|old town}}',
 '*{{fi}}: {{Ü|fi|vanhakaupunki}}',
 '*{{fr}}: {{Ü|fr|vieille ville}} {{f}}, {{Ü|fr|centre historique}} {{m}}',
 '*{{it}}: {{Ü|it|città vecchia}} {{f}}, {{Ü|it|centro storico}} {{m}}',
 '*{{ja}}: {{Üt|ja|旧市街|きゅうしがい, kyōshigai}}',
 '*{{ca}}: {{Ü|ca|centre històric}} {{m}}',
 '*{{hr}}: {{Ü|hr|stari grad}} {{m}}, {{Ü|hr|povijesna jezgra}} {{f}}',
 '*{{lt}}: {{Ü|lt|senamiestis}}',
 '*{{lb}}: {{Ü|lb|Alstad}} {{f}}',
 '*{{nl}}: {{Ü|nl|historisch centrum}} {{n}}, {{Ü|nl|oudestad}} {{f}}',
 '*{{pt}}: {{Ü|pt|bairro histórico}} {{m}}, {{Ü|pt|centro histórico}} {{m}}',
 '*{{ru}}: {{Üt|ru|старый город}} {{m}}',
 '*{{sv}}: {{Ü|sv|gammal stadskärna}} {{u}}',
 '*{{es}}: {{Ü|es|casco histórico}} {{m}}',
 '*{{tr}}: {{Ü|tr|eski şehir}}',
 '*{{hu}}: {{Ü|hu|óváros}}',
 '}}',
 '',
 '{{Referenzen}}',
 ':[1] {{Wikipedia|Altstadt}}',
 ':[1] {{Ref-Grimm|Altstadt}}',
 ':[1] {{Ref-DWDS|Altstadt}}',
 ':[1] {{Ref-UniLeipzig|Altstadt}}',
 ':[1] {{Ref-FreeDictionary|Altstadt}}',
 '',
 '{{Quellen}}',
 '',
 '=== {{Wortart|Substantiv|Deutsch}}, {{Wortart|Toponym|Deutsch}} {{n}} ===',
 '',
 '{{Deutsch Toponym Übersicht',
 '}}',
 '',
 '{{Worttrennung}}',
 ':Alt·stadt, {{kPl.}}',
 '',
 '{{Aussprache}}',
 ':{{IPA}} {{Lautschrift|ˈaltˌʃtat}}',
 ':{{Hörbeispiele}} {{Audio|De-Altstadt.ogg}}',
 ':{{Reime}} {{Reim|altʃtat|Deutsch}}',
 '',
 '{{Bedeutungen}}',
 ':[1] Ort im [[Saarland]], Deutschland',
 '',
 '{{Beispiele}}',
 ":[1] Anne wurde in ''Altstadt'' geboren.",
 '',
 '{{Referenzen}}',
 ':[1] {{Wikipedia|Altstadt (Kirkel)}}']